// Uncountable Nouns academy: the Small Common Words academy rebuilt for 420 uncountable nouns.
// Same journey (one scene at a time), same lesson steps (Learn → Together → Picture → Meaning), same picture library,
// review notebook, read-aloud and focus screen; three scenes per noun instead of fifty, grouped by category.
import {recordAnswer} from '../common-words/engine.js';
import {loadSave, saveBack} from './nouns-save.js';
import {NOUNS, UNITS, SETS, PER, TOTAL, SOURCES, sceneAt, nextIndex, stateFor, checkpoint, canOpen, complete} from './content.js';
import {illustration, describe, escape as esc} from './art.js';
const app = document.querySelector('#app'), initial = loadSave(localStorage);
let save = initial.save, blocked = !!initial.error, view = 'home', current = null, opposite = false, options = [], choiceOrder = null;
// Session countdown for a timed visit (#continue): 5 minutes, or ?minutes=N; counts only while the page is visible.
const SESSION_KEY = 'un-session-left'; let session = null, SESSION_MIN = 5;
function startSession(){ const m = Math.max(1, Math.min(60, Number(new URLSearchParams(location.search).get('minutes')) || 5)); SESSION_MIN = m; session = { left: m * 60 }; try { sessionStorage.setItem(SESSION_KEY, String(session.left)); } catch {} }
try { const left = Number(sessionStorage.getItem(SESSION_KEY)); if (left > 0 || sessionStorage.getItem(SESSION_KEY) === '0') session = { left: Math.max(0, left) }; } catch {}
const clockText = () => session ? `⏱ ${Math.floor(session.left / 60)}:${String(session.left % 60).padStart(2, '0')}` : '';
const timeUp = () => !!session && session.left <= 0;
setInterval(() => { if (!session || session.left <= 0 || document.visibilityState !== 'visible') return; session.left--; try { sessionStorage.setItem(SESSION_KEY, String(session.left)); } catch {}
 const el = document.querySelector('#focus-timer'); if (el) { el.textContent = clockText(); el.classList.toggle('low', session.left <= 60); }
 if (session.left === 0) { announce('Time’s up — great work!'); if (view === 'lesson') lesson(); } }, 1000);
const p = () => save.profiles.find(x => x.id === save.active), state = () => stateFor(p());
let announceTimer = 0; function announce(s){ const el = document.querySelector('#status'); el.textContent = s; clearTimeout(announceTimer); if (s) announceTimer = setTimeout(() => { if (el.textContent === s) el.textContent = ''; }, 4000); }
function persist(){ if (blocked) return false; try { saveBack(localStorage, save); return true; } catch { blocked = true; announce('Saving is unavailable on this device right now.'); return false; } }
// The voice chosen in WordRaiders Settings, else the best English voice (Premium or Enhanced first).
function voiceFor(){ try { const all = speechSynthesis.getVoices().filter(v => /^en/i.test(v.lang)); let name = ''; try { name = JSON.parse(localStorage.getItem(save.key) || '{}')?.settings?.voice || ''; } catch {}
 const q = v => { const t = v.name + ' ' + (v.voiceURI || ''); return /premium/i.test(t) ? 8 : /enhanced|natural|neural|online/i.test(t) ? 6 : /compact/i.test(t) ? -4 : 0; };
 return all.find(v => v.name === name && q(v) >= Math.max(...all.filter(w => w.name === name).map(q))) || all.sort((a, b) => q(b) - q(a) + (/en[-_]US/i.test(b.lang) ? 2 : 0) - (/en[-_]US/i.test(a.lang) ? 2 : 0))[0] || null; } catch { return null; } }
function say(t){ if (!('speechSynthesis' in window)) { announce('Read-aloud is not available in this browser. All lesson text is on screen.'); return; } speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(t); const v = voiceFor(); u.lang = v?.lang || 'en-US'; if (v) u.voice = v; u.rate = .82; speechSynthesis.speak(u); }
const btn = (label, action, attrs = '', cls = '') => `<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const nf = n => n.toLocaleString();
function shell(body){ const count = Object.keys(state().completed).length; app.innerHTML = `<header><a href="../?journey" class="brand"><span class="brand-icon">≈<span>∞</span></span><span>UNCOUNTABLE<b>NOUNS</b></span></a><div class="profile"><span>${save.player ? 'Playing as' : 'Guest'} <b>${esc(p().name)}</b></span><a href="../?journey">${save.player ? 'Back to WordRaiders ↗' : 'Open WordRaiders to save to a player ↗'}</a></div></header><nav aria-label="Academy navigation">${btn('My journey', 'home', '', view === 'home' ? 'active' : '')}${btn('Picture library', 'library', '', view === 'library' ? 'active' : '')}${btn('Review meanings', 'review', '', view === 'review' ? 'active' : '')}<span>${nf(count)} / ${nf(TOTAL)} scenes</span></nav><main id="main" tabindex="-1">${blocked ? '<p class="warning">Progress cannot be saved here. Your existing progress has not been overwritten.</p>' : ''}${body}</main><footer><a href="../?journey">← WordRaiders</a><span>Original illustrations • One noun at a time</span></footer>`; }
function focus(body, label = ''){ app.innerHTML = `<div class="focus-bar"><a class="focus-back" href="../?journey">← WordRaiders</a><span class="focus-word">${label}</span><span class="focus-timer" id="focus-timer" ${session ? '' : 'hidden'}>${clockText()}</span></div><main id="main" class="focus-main" tabindex="-1">${blocked ? '<p class="warning">Progress cannot be saved here.</p>' : ''}${timeUp() ? `<p class="time-up" role="status">Time’s up — great work! Finish this scene, then head Home.</p>` : ''}${body}</main>`; }
const setRange = set => [set[0].index * PER, (set[set.length - 1].index + 1) * PER];
function home(){ view = 'home'; const c = state().completed, n = nextIndex(c), count = Object.keys(c).length, resume = state().checkpoint, nextCat = n === null ? -1 : sceneAt(n).noun.cat;
 shell(`<section class="hero"><div><p class="eyebrow">THINGS WE DON’T COUNT ONE BY ONE</p><h1>See the meaning.<br>Learn how we count it.</h1><p>Water, advice, furniture, happiness: we don’t say “a water” or “three advices”. Each noun gets a picture of what it means, a picture of how much, and a way to count it. Your journey has a finish line: <strong>${nf(TOTAL)} illustrated scenes.</strong></p><div class="actions">${n !== null ? btn(resume ? 'Continue my journey →' : 'Start my journey →', 'open', `data-index="${resume?.index ?? n}"`, 'primary') : btn('Explore my completed academy', 'library', '', 'primary')}${btn('How this academy works', 'about')}</div><p class="small">${nf(NOUNS.length)} nouns × 3 pictured scenes, in seven categories.</p></div><div class="hero-art">${illustration(sceneAt(NOUNS.findIndex(x => x.word === 'water') * PER + 2))}<span>Count the glasses, not the water.</span></div></section><section class="progress-card"><div><b>${nf(count)}</b><span>scenes completed</span></div><progress max="${TOTAL}" value="${count}" aria-label="Academy completion"></progress><strong>${Math.round(count / TOTAL * 100)}%</strong></section><div class="section-title"><div><p class="eyebrow">SEVEN CATEGORIES</p><h2>${n === null ? 'Your academy journey is complete.' : 'One noun at a time.'}</h2></div><span>3 scenes per noun</span></div><div class="chapters">${UNITS.map(([title, sub, emoji], u) => { const all = NOUNS.filter(x => x.cat === u), done = all.reduce((a, x) => a + [0, 1, 2].filter(k => c['n' + (x.index * PER + k)]).length, 0), total = all.length * PER;
  return `<details ${u === nextCat ? 'open' : ''}><summary><span class="chapter-number">${done === total ? '✓' : u + 1}</span><div><h3>${emoji} ${title}</h3><p>${done} / ${total} scenes • ${all.length} nouns • ${esc(sub)}</p></div><span>⌄</span></summary><div class="units">${SETS[u].map((set, si) => { const [a, b] = setRange(set), d = Array.from({ length: b - a }, (_, j) => !!c['n' + (a + j)]).filter(Boolean).length, index = Array.from({ length: b - a }, (_, j) => a + j).find(i => !c['n' + i]) ?? a, ok = canOpen(p(), index);
   return `<button data-action="open" data-index="${index}" ${ok ? '' : 'disabled'}><span>${d === b - a ? '✓' : si + 1}</span><div><b>${esc(set[0].word)} → ${esc(set[set.length - 1].word)}</b><small>${set.length} nouns</small><small>${d}/${b - a} scenes</small></div><span>${ok ? '→' : 'Locked'}</span></button>`; }).join('')}</div></details>`; }).join('')}</div><p class="note">Each scene includes teaching, guided practice, a picture check, and a meaning check. A miss goes back to teaching. Every picture can be explored in Picture library.</p>`); }
function open(index){ if (!canOpen(p(), index)) { announce('Finish your current scene to open this one. You can preview every illustration in Picture library.'); return; } current = sceneAt(index); if (state().checkpoint?.index !== index) state().checkpoint = checkpoint(index); opposite = false; choiceOrder = null; persist(); view = 'lesson'; lesson(); }
// A noun's three scenes: once its independent checks are right MASTERY times in a row, the rest of the set counts as done.
const MASTERY = 4;
function knowsWord(s){ const r = p().records['nouns.' + s.use.id]; if (!r || r.streak < MASTERY) return false; const c = state().completed, start = s.index - s.index % PER, now = Date.now(); let skipped = 0;
 for (let i = start; i < start + PER; i++) if (!c['n' + i]) { c['n' + i] = now; skipped++; } return skipped > 0; }
function wordProgress(s){ const c = state().completed, start = s.index - s.index % PER; return Array.from({ length: PER }, (_, i) => c['n' + (start + i)] || start + i === s.index ? '●' : '○').join(''); }
function answerOptions(){ if (!choiceOrder) choiceOrder = Math.random() < .5 ? [current.use.scene, current.use.wrong] : [current.use.wrong, current.use.scene]; return choiceOrder; }
function lesson(){ const s = current, w = state().checkpoint; if (!s || !w) { home(); return; } const u = s.use, phase = w.phase;
 if (phase === 'done') { const was = !!state().completed[s.id]; complete(p(), s.index); const known = !was && knowsWord(s); persist(); const n = nextIndex(state().completed);
  focus(`<section class="celebration"><div class="medal">✦</div><p class="eyebrow">${known ? 'NOUN LEARNED' : 'SCENE COMPLETE'}</p><h1>${known ? `You know “${esc(u.word)}”!` : 'You made the connection.'}</h1><p>${esc(s.sentence)}</p><p>${was ? 'Review finished. Your completion is preserved.' : known ? `Right ${MASTERY} times in a row, so its other scenes count as done. On to the next noun. +10 XP` : 'Both independent checks passed. +10 XP'}</p>${timeUp() ? `<p class="time-done">✓ ${SESSION_MIN} minute${SESSION_MIN === 1 ? '' : 's'} done!</p><div class="actions"><a class="button primary" href="../?journey&today=next">Next task ▸</a><a class="button" href="../?journey">Back to Home</a>${n !== null ? btn('Keep going →', 'open', `data-index="${n}"`) : ''}</div>` : `<div class="actions">${n !== null ? btn(known ? 'Next noun →' : 'Next scene →', 'open', `data-index="${n}"`, 'primary') : btn('See my completed journey', 'home', '', 'primary')}<a class="button" href="../?journey">Back to WordRaiders</a></div>`}</section>`, esc(u.word)); return; }
 const feedback = w.feedback; let body = '';
 if (phase === 'learn') { body = `<div class="lesson-grid"><section class="scene-card">${illustration(s, opposite ? u.wrong : u.scene, { legend: !opposite })}<p class="caption">${esc(opposite ? 'Compare: ' + describe(s, u.wrong) : s.sentence)}</p>${btn(opposite ? 'Show the lesson picture again' : 'Compare a different picture', 'compare', '', 'quiet')}</section><section class="explanation"><span class="word-tag">${esc(u.word)}</span><h1>${esc(u.heading)}</h1><p class="definition">${esc(u.meaning)}</p><div class="notice"><b>Notice the difference</b><p>${esc(u.contrast)}</p></div>${feedback ? '<p class="warning">Let’s look again. Read or listen to the explanation, then try with help.</p>' : ''}<div class="actions">${btn('Read this to me', 'listen')}${btn('Practice with help →', 'teach-next', '', 'primary')}</div><p class="small">Say the sentence. Point to the part of the picture that makes it true.</p></section></div>`; }
 else if ((phase === 'guided' || phase === 'picture') && feedback) { body = `<div class="answered"><p class="sentence">${esc(s.sentence)}</p><div class="picture-choice correct answered-pic">${illustration(s, u.scene, { legend: false })}</div></div>`; }
 else if (phase === 'guided' || phase === 'picture') { const guided = phase === 'guided'; body = `<div class="prompt"><p class="eyebrow">${guided ? 'PRACTICE WITH HELP' : 'INDEPENDENT CHECK 1 OF 2'}</p><h1>Which picture matches?</h1>${btn(`${esc(s.sentence)} <span aria-hidden="true">🔊</span>`, 'listen', 'aria-label="Read the sentence aloud"', 'sentence say')}${guided ? `<p class="hint">${esc(u.meaning)}</p>` : ''}</div><div class="picture-options">${answerOptions().map((kind, i) => `<div><button class="picture-choice" data-action="answer-picture" data-kind="${kind}" aria-label="Picture ${i + 1}: ${esc(describe(s, kind))}"><span class="option-number">${i + 1}</span>${illustration(s, kind, { caption: false, legend: false })}</button></div>`).join('')}</div>`; }
 else if (phase === 'meaning' && feedback) { body = `<div class="answered"><section class="scene-card">${illustration(s, u.scene, { legend: false })}<p class="caption">${esc(s.sentence)}</p></section><p class="answered-meaning"><b>“${esc(u.word)}” here:</b> ${esc(u.right)}</p></div>`; }
 else if (phase === 'meaning') { options = [{ id: u.id, use: u.right }, { id: 'wrong', use: u.incorrect }]; if (s.index % 2) options.reverse(); body = `<div class="meaning-grid"><section class="scene-card">${illustration(s, u.scene, { legend: false })}<p class="caption">${esc(s.sentence)}</p></section><section><p class="eyebrow">INDEPENDENT CHECK 2 OF 2</p><h1>${btn(`${esc(u.ask)} <span aria-hidden="true">🔊</span>`, 'listen', 'aria-label="Read the question aloud"', 'say')}</h1><div class="meaning-options">${options.map(x => btn(esc(x.use), 'answer-meaning', `data-id="${x.id}"`)).join('')}</div></section></div>`; }
 if (feedback && phase !== 'learn') body += `<section class="feedback ${feedback.correct ? 'good' : 'wrong'}" role="status"><b>${feedback.correct ? (phase === 'guided' ? 'You found it with help.' : 'That fits.') : 'Let’s make the meaning clearer.'}</b><p>${esc(feedback.correct ? u.meaning : u.contrast)}</p>${btn(feedback.correct ? 'Continue →' : 'Teach me again →', 'continue', '', 'primary')}</section>`;
 focus(`<ol class="steps">${[['learn', 'Learn'], ['guided', 'Together'], ['picture', 'Picture'], ['meaning', 'Meaning']].map(([key, label], i) => `<li class="${phase === key ? 'active' : ''}" ${phase === key ? 'aria-current="step"' : ''}>${i + 1}. ${label}</li>`).join('')}</ol>${body}`, `${esc(u.word)} <small>${wordProgress(s)}</small>`);
}
const KIND_NAMES = ['What it means', 'A lot of …', 'Counting / a little'];
function library(){ view = 'library'; shell(`<p class="eyebrow">ALL ${nf(TOTAL)} SCENES ARE AVAILABLE TO EXPLORE</p><h1>Your illustrated noun library.</h1><p>Choose a noun and a scene. Library previews do not grant completion.</p><div class="filters"><label>Noun<select id="noun">${UNITS.map(([t], c) => `<optgroup label="${esc(t)}">${NOUNS.filter(n => n.cat === c).map(n => `<option value="${n.index}">${esc(n.word)}</option>`).join('')}</optgroup>`).join('')}</select></label><label>Scene<select id="kind">${KIND_NAMES.map((k, i) => `<option value="${i}">${k}</option>`).join('')}</select></label></div><div id="library-scene"></div>`); preview(); }
function preview(){ const ni = Number(document.querySelector('#noun').value), k = Number(document.querySelector('#kind').value), index = ni * PER + k, s = sceneAt(index);
 document.querySelector('#library-scene').innerHTML = `<div class="lesson-grid"><section class="scene-card">${illustration(s)}<p class="caption">${esc(s.sentence)}</p></section><section class="explanation"><span class="word-tag">${esc(s.use.word)}</span><h2>${esc(s.use.heading)}</h2><p>${esc(s.use.meaning)}</p><p>${esc(s.use.contrast)}</p><div class="actions">${btn('Read this scene', 'preview-listen', `data-index="${index}"`)}${btn('Download illustration', 'download', `data-index="${index}"`)}${canOpen(p(), index) ? btn('Open lesson', 'open', `data-index="${index}"`, 'primary') : ''}</div><p class="small">Illustration ${index + 1}/${nf(TOTAL)} • original SVG diagram</p></section></div>`; }
function review(){ view = 'review'; const es = NOUNS.filter(n => p().records['nouns.' + n.id]); shell(`<p class="eyebrow">KEEP THE MEANING WITH YOU</p><h1>Return, remember, reconnect.</h1><p>Scene completion records what you finished. This notebook separately shows answers across days and nouns that need another look.</p><div class="review-list">${es.length ? es.map(n => { const r = p().records['nouns.' + n.id], due = r.repair || r.due <= Date.now(), strong = r.days.length >= 3 && r.streak >= 4 && !due; const index = n.index * PER;
  return `<article><span class="word-tag">${esc(n.word)}</span><div><h2>${esc(n.kid)}</h2><p>${r.days.length} successful practice dates • ${r.correct}/${r.attempts} independent answers</p><p>${due ? 'Review due' : strong ? 'Review current across three or more days' : 'Building evidence over time'}</p></div>${state().completed['n' + index] ? btn('Review a scene', 'open', `data-index="${index}"`) : btn('Continue learning', 'open', `data-index="${nextIndex(state().completed)}"`)}</article>`; }).join('') : '<p class="empty">Your first independent answer will start your review notebook.</p>'}</div><p class="note">Review timing uses the game’s 1, 3, 7, 14, 30 and 60-day schedule. These are learning records, not a validated test.</p>`); }
function about(){ view = 'about'; shell(`<p class="eyebrow">HOW THE ACADEMY WORKS</p><h1>Some things we don’t count one by one.</h1><p>An uncountable noun names a mass, a substance, an activity, a feeling or a collection: water, rice, advice, furniture, happiness. We don’t put “a” or a number in front of it, and we don’t add -s. We say “some water”, “a lot of advice”, or we count a unit: “a glass of water”, “three pieces of furniture”.</p><p>This academy has ${nf(NOUNS.length)} common uncountable nouns in seven categories. Each noun has three scenes: a picture of what it means, a picture of how much (a lot of / a little), and a way to count it with a unit when English has one. ${nf(TOTAL)} scenes in all.</p><p>Every scene teaches first, offers guided practice, then checks the picture and the meaning independently. A miss returns to teaching.</p><p>Some nouns are countable in another meaning (a coffee = one cup; a business = one company). The lessons teach the uncountable meaning and note the other one where it matters.</p><h2>Grammar references</h2><ul>${SOURCES.map(([n, url]) => `<li><a href="${url}" target="_blank" rel="noopener">${esc(n)}</a></li>`).join('')}</ul><p>Explanations, kid meanings, sentences and artwork are original. Definitions follow the Common Uncountable Nouns study reference.</p>`); }
function submit(correct, form){ const w = state().checkpoint; if (!w || w.feedback) return; w.feedback = { correct }; if (w.phase !== 'guided') p().records['nouns.' + current.use.id] = recordAnswer(p().records['nouns.' + current.use.id], { correct, form }); persist(); lesson(); window.scrollTo({ top: 0, behavior: 'instant' }); }
document.addEventListener('click', e => { const b = e.target.closest('[data-action]'); if (!b || b.disabled) return; const a = b.dataset.action;
 if (['home', 'library', 'review', 'about'].includes(a)) { window.speechSynthesis?.cancel(); ({ home, library, review, about })[a](); }
 else if (a === 'open') open(Number(b.dataset.index));
 else if (a === 'preview-listen') { const s = sceneAt(Number(b.dataset.index)); say(s.sentence + ' ' + s.use.meaning); }
 else if (a === 'download') { const s = sceneAt(Number(b.dataset.index)), blob = new Blob([illustration(s)], { type: 'image/svg+xml' }), url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = `uncountable-${s.index + 1}-${s.use.id}-${s.kind}.svg`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
 else if (current && state().checkpoint) { const w = state().checkpoint;
  if (a === 'listen') { say(current.sentence + '. ' + (w.phase === 'learn' || w.phase === 'guided' ? current.use.meaning + ' ' + current.use.contrast : w.phase === 'meaning' ? current.use.ask + ' ' + options.map(x => x.use).join('. ') : 'Which picture matches? ' + answerOptions().map((k, i) => 'Picture ' + (i + 1) + ': ' + describe(current, k)).join('. '))); return; }
  if (a === 'compare') { opposite = !opposite; lesson(); return; }
  if (a === 'teach-next' && w.phase === 'learn') { w.phase = 'guided'; w.feedback = null; choiceOrder = null; }
  else if (a === 'answer-picture' && ['guided', 'picture'].includes(w.phase)) { submit(b.dataset.kind === current.use.scene, 'context'); return; }
  else if (a === 'answer-meaning' && w.phase === 'meaning') { submit(b.dataset.id === current.use.id, 'meaning'); return; }
  else if (a === 'continue' && w.feedback) { if (!w.feedback.correct) w.phase = 'learn'; else { w.phase = { guided: 'picture', picture: 'meaning', meaning: 'done' }[w.phase]; w.feedback = null; } choiceOrder = null; }
  persist(); lesson();
 }
 window.scrollTo({ top: 0, behavior: 'instant' });
});
document.addEventListener('change', e => { if (e.target.id === 'noun' || e.target.id === 'kind') preview(); });
window.addEventListener('storage', e => { if (e.key === save.mineKey) { const latest = loadSave(localStorage); if (!latest.error) { save = latest.save; current = null; home(); announce('Progress was updated in another tab. Your saved place is ready.'); } } });
(({ library, review, about })[location.hash.slice(1)] || home)();
if (location.hash === '#continue') { startSession(); const n = nextIndex(state().completed), resume = state().checkpoint, index = resume?.index ?? n; if (index !== null && index !== undefined) open(index); history.replaceState(null, '', location.pathname + location.search); }
