import {recordAnswer,DAY} from './engine.js';
import {loadSave,saveBack} from './wordraiders-save.js';
import {USES,UNITS,OBJECTS,TOTAL,SOURCES,sceneAt,nextIndex,stateFor,checkpoint,canOpen,complete} from './content.js';
import {illustration,describe,escape as esc} from './art.js';
const app=document.querySelector('#app'),initial=loadSave(localStorage);let save=initial.save,blocked=!!initial.error,view='home',current=null,opposite=false,options=[],choiceOrder=null;
const p=()=>save.profiles.find(x=>x.id===save.active),state=()=>stateFor(p());
function announce(s){document.querySelector('#status').textContent=s;}
function persist(){if(blocked)return false;try{saveBack(localStorage,save);return true;}catch{blocked=true;announce('Saving is unavailable. Export a backup from WordRaiders settings.');return false;}}
function say(t){if(!('speechSynthesis'in window)){announce('Read-aloud is not available in this browser. All lesson text is on screen.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u);}
const btn=(label,action,attrs='',cls='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
function shell(body){const count=Object.keys(state().completed).length;app.innerHTML=`<header><a href="../" class="brand"><span class="brand-icon">a<span>b</span></span><span>SMALL COMMON WORD<b>ACADEMY</b></span></a><div class="profile"><span>${save.player?'Playing as':'Guest'} <b>${esc(p().name)}</b></span><a href="../">${save.player?'Back to WordRaiders ↗':'Open WordRaiders to save to a player ↗'}</a></div></header><nav aria-label="Academy navigation">${btn('My journey','home','',view==='home'?'active':'')}${btn('Picture library','library','',view==='library'?'active':'')}${btn('Review meanings','review','',view==='review'?'active':'')}<span>${count.toLocaleString()} / 3,000 scenes</span></nav><main id="main" tabindex="-1">${blocked?'<p class="warning">Progress cannot be saved here. Your existing backup has not been overwritten. Use Linguistics Quest → Profiles to manage saving.</p>':''}${body}</main><footer><a href="../">← Linguistics Quest</a><span>Original illustrations • One relationship at a time</span></footer>`;}
function home(){view='home';const c=state().completed,n=nextIndex(c),count=Object.keys(c).length,resume=state().checkpoint;
 shell(`<section class="hero"><div><p class="eyebrow">THE LITTLE WORDS. THE BIG PICTURE.</p><h1>See the meaning.<br>Build your foundation.</h1><p>A picture, a clear explanation, and a chance to show what you understand. Your journey has a finish line: <strong>3,000 illustrated scenes.</strong></p><div class="actions">${n!==null?btn(resume?'Continue my journey →':'Start my journey →','open',`data-index="${resume?.index??n}"`,'primary'):btn('Explore my completed academy','library','','primary')}${btn('How this academy works','about')}</div><p class="small">60 common-word uses × 50 pictured contexts. These are 3,000 scenes, not 3,000 different definitions.</p></div><div class="hero-art">${illustration(sceneAt(0))}<span>“in” connects the object to its location.</span></div></section><section class="progress-card"><div><b>${count.toLocaleString()}</b><span>scenes completed</span></div><progress max="3000" value="${count}" aria-label="Academy completion"></progress><strong>${Math.round(count/30)}%</strong></section><div class="section-title"><div><p class="eyebrow">YOUR TEN EXPEDITIONS</p><h2>${n===null?'Your academy journey is complete.':'One small scene at a time.'}</h2></div><span>300 scenes per expedition</span></div><div class="chapters">${Array.from({length:10},(_,r)=>{const done=Array.from({length:300},(_,j)=>!!c['a'+(r*300+j)]).filter(Boolean).length;return `<details ${n!==null&&Math.floor(n/300)===r?'open':''}><summary><span class="chapter-number">${done===300?'✓':r+1}</span><div><h3>${['First discoveries','New objects, familiar meanings','Growing connections','Everyday explorers','Clearer pictures','Meaning detectives','Confident connections','Transfer trail','Deep understanding','The final expedition'][r]}</h3><p>${done} / 300 scenes • ${OBJECTS[r*5].noun} to ${OBJECTS[r*5+4].noun}</p></div><span>⌄</span></summary><div class="units">${UNITS.map(([title,sub],u)=>{let start=r*300+u*50,done=Array.from({length:50},(_,j)=>!!c['a'+(start+j)]).filter(Boolean).length;let index=Array.from({length:50},(_,j)=>start+j).find(i=>!c['a'+i])??start;return `<button data-action="open" data-index="${index}" ${canOpen(p(),index)?'':'disabled'}><span>${done===50?'✓':u+1}</span><div><b>${title}</b><small>${sub}</small><small>${done}/50 scenes</small></div><span>${canOpen(p(),index)?'→':'Locked'}</span></button>`;}).join('')}</div></details>`;}).join('')}</div><p class="note">Each scene includes teaching, guided practice, a picture check, and a meaning check. Completion opens the next scene. Later reviews check retention separately. Progress stays with this profile in this browser; export family backups from Linguistics Quest.</p>`);
}
function open(index){if(!canOpen(p(),index)){announce('Finish your current scene to open this one. You can preview every illustration in Picture library.');return;}current=sceneAt(index);if(state().checkpoint?.index!==index)state().checkpoint=checkpoint(index);opposite=false;choiceOrder=null;persist();view='lesson';lesson();}
function answerOptions(){if(!choiceOrder){choiceOrder=Math.random()<.5?[current.use.scene,current.use.wrong]:[current.use.wrong,current.use.scene];}return choiceOrder;}
function lesson(){const s=current,w=state().checkpoint;if(!s||!w){home();return;}const u=s.use,phase=w.phase;
 if(phase==='done'){const was=!!state().completed[s.id];complete(p(),s.index);persist();const n=nextIndex(state().completed);shell(`<section class="celebration"><div class="medal">✦</div><p class="eyebrow">${(s.index+1)%300===0?'EXPEDITION COMPLETE':'SCENE COMPLETE'}</p><h1>You made the connection.</h1><p>${esc(s.sentence)}</p><p>${was?'Review finished. Your completion is preserved.':'Both independent checks passed. +10 XP'}</p><div class="actions">${n!==null?btn('Next scene →','open',`data-index="${n}"`,'primary'):btn('See my completed journey','home','','primary')}${btn('Back to my journey','home')}</div></section>`);return;}
 const feedback=w.feedback;let body='';
 if(phase==='learn'){body=`<div class="lesson-grid"><section class="scene-card">${illustration(s,opposite?u.wrong:u.scene,{caption:!opposite})}<p class="caption">${esc(opposite?describe(s,u.wrong):s.sentence)}</p>${btn(opposite?'Show the meaning again':'Compare a different relationship','compare','','quiet')}</section><section class="explanation"><span class="word-tag">${esc(u.word)}</span><h1>${esc(u.use)}</h1><p class="definition">${esc(u.meaning)}</p><div class="notice"><b>Notice the difference</b><p>${esc(u.contrast)}</p></div>${feedback?'<p class="warning">Let’s look again. Read or listen to the explanation, then try with help.</p>':''}<div class="actions">${btn('Read this to me','listen')}${btn('Practice with help →','teach-next','','primary')}</div><p class="small">Say the sentence. Point to the part of the picture that makes it true.</p></section></div>`;
 }else if(phase==='guided'||phase==='picture'){const guided=phase==='guided';body=`<div class="prompt"><p class="eyebrow">${guided?'PRACTICE WITH HELP':'INDEPENDENT CHECK 1 OF 2'}</p><h1>Which picture matches?</h1><p class="sentence">${esc(s.sentence)}</p>${guided?`<p class="hint">${esc(u.meaning)}</p>`:''}<div class="actions">${btn('Read the sentence','listen')}${!feedback?btn('Teach me again','reteach','','quiet'):''}</div></div><div class="picture-options">${answerOptions().map((kind,i)=>`<div><button class="picture-choice ${feedback&&kind===u.scene?'correct':''}" data-action="answer-picture" data-kind="${kind}" ${feedback?'disabled':''} aria-label="Choose picture ${i+1}"><span class="option-number">${i+1}</span>${illustration(s,kind,{caption:false})}</button><details class="description"><summary>Describe picture ${i+1}</summary><p>${esc(describe(s,kind))}</p></details></div>`).join('')}</div>${guided?'<p class="small center">Use the explanation while you practice. This answer does not count toward completion.</p>':''}`;
 }else if(phase==='meaning'){options=[{id:u.id,use:u.use},{id:'wrong',use:u.incorrect}];if(s.index%2)options.reverse();body=`<div class="meaning-grid"><section class="scene-card">${illustration(s)}<p class="caption">${esc(s.sentence)}</p></section><section><p class="eyebrow">INDEPENDENT CHECK 2 OF 2</p><h1>What does “${esc(u.word)}” mean here?</h1><div class="meaning-options">${options.map(x=>btn(esc(x.use),'answer-meaning',`data-id="${x.id}" ${feedback?'disabled':''}`,feedback&&x.id===u.id?'correct':'')).join('')}</div><div class="actions">${btn('Read this to me','listen')}${!feedback?btn('Teach me again','reteach','','quiet'):''}</div></section></div>`;}
 if(feedback&&phase!=='learn')body+=`<section class="feedback ${feedback.correct?'good':'wrong'}" role="status"><b>${feedback.correct?(phase==='guided'?'You found it with help.':'That relationship fits.'):'Let’s make the meaning clearer.'}</b><p>${esc(feedback.correct?u.meaning:u.contrast)}</p>${btn(feedback.correct?'Continue →':'Teach me again →','continue','','primary')}</section>`;
 shell(`<div class="lesson-top">${btn('← Save & return','home','','quiet')}<span>Expedition ${s.round+1} • Scene ${s.index+1} / 3,000</span></div><ol class="steps">${[['learn','Learn'],['guided','Together'],['picture','Picture check'],['meaning','Meaning check']].map(([key,label],i)=>`<li class="${phase===key?'active':''}" ${phase===key?'aria-current="step"':''}>${i+1}. ${label}</li>`).join('')}</ol>${body}`);
}
function library(){view='library';shell(`<p class="eyebrow">ALL 3,000 SCENES ARE AVAILABLE TO EXPLORE</p><h1>Your illustrated word library.</h1><p>Choose a word use and an object. Each pairing has its own sentence and original illustration. Library previews do not grant completion.</p><div class="filters"><label>Word and meaning<select id="use">${USES.map((u,i)=>`<option value="${i}">${esc(u.word)} — ${esc(u.use)}</option>`).join('')}</select></label><label>Illustrated object<select id="object">${OBJECTS.map((o,i)=>`<option value="${i}">${esc(o.noun)}</option>`).join('')}</select></label></div><div id="library-scene"></div>`);preview();}
function preview(){const ui=Number(document.querySelector('#use').value),oi=Number(document.querySelector('#object').value),index=Math.floor(oi/5)*300+ui*5+oi%5,s=sceneAt(index);document.querySelector('#library-scene').innerHTML=`<div class="lesson-grid"><section class="scene-card">${illustration(s)}<p class="caption">${esc(s.sentence)}</p></section><section class="explanation"><span class="word-tag">${esc(s.use.word)}</span><h2>${esc(s.use.use)}</h2><p>${esc(s.use.meaning)}</p><p>${esc(s.use.contrast)}</p><div class="actions">${btn('Read this scene','preview-listen',`data-index="${index}"`)}${btn('Download illustration','download',`data-index="${index}"`)}${canOpen(p(),index)?btn('Open lesson','open',`data-index="${index}"`,'primary'):''}</div><p class="small">Illustration ${index+1}/3,000 • original SVG diagram</p></section></div>`;}
function review(){view='review';const es=USES.filter(u=>p().records['academy.'+u.id]);shell(`<p class="eyebrow">KEEP THE MEANING WITH YOU</p><h1>Return, remember, reconnect.</h1><p>Scene completion records what you finished. This notebook separately shows answers across days and meanings that need another look.</p><div class="review-list">${es.length?es.map(u=>{let r=p().records['academy.'+u.id],due=r.repair||r.due<=Date.now(),strong=r.days.length>=3&&r.streak>=4&&r.forms.includes('context')&&r.forms.includes('meaning')&&!due;let index=Object.keys(state().completed).map(x=>Number(x.slice(1))).find(i=>sceneAt(i).use.id===u.id);return `<article><span class="word-tag">${esc(u.word)}</span><div><h2>${esc(u.use)}</h2><p>${r.days.length} successful practice dates • ${r.correct}/${r.attempts} independent answers</p><p>${due?'Review due':strong?'Review current across three or more days':'Building evidence over time'}</p></div>${index!==undefined?btn('Review a scene','open',`data-index="${index}"`):btn('Continue learning','open',`data-index="${nextIndex(state().completed)}"`)}</article>`;}).join(''):'<p class="empty">Your first independent answer will start your review notebook.</p>'}</div><p class="note">Review timing uses the game’s 1, 3, 7, 14, 30 and 60-day schedule. These are learning records, not a validated test of vocabulary mastery.</p>`);}
function about(){view='about';shell(`<p class="eyebrow">HOW THE ACADEMY WORKS</p><h1>Small words deserve clear pictures.</h1><p>This academy contains 60 selected uses of common words and phrases. Each appears in 50 object contexts, giving 3,000 distinct illustrated scenes. Multiple contexts practice transfer of a meaning; they are not counted as new dictionary definitions.</p><p>The journey has ten expeditions. Each has six units of 50 scenes. Every scene teaches first, offers guided practice, then checks picture understanding and meaning independently. A miss returns to teaching. All illustrations can be explored freely in Picture library.</p><p>Vector diagrams use boundaries, arrows, group counts, and labels to make relationships visible. Some abstract uses need labels and explanation as well as pictures. Arrows show either movement or pointing, as described in the lesson. Faint objects mark earlier positions.</p><p>This is an original curriculum inspired by the idea of illustrated common-word learning. No illustrations, definitions, or page layouts from Small Common Words Defined have been reproduced. It does not claim to cover all English uses or idioms, or a full school curriculum.</p><h2>Grammar references</h2><ul>${SOURCES.map(([n,url])=>`<li><a href="${url}" target="_blank" rel="noopener">${n}</a></li>`).join('')}</ul><p>Explanations and artwork are original. Profiles and progress are shared with Linguistics Quest on this browser. Use its Profiles screen for creation, renaming, and validated backup export/import.</p>${btn('Start exploring','home','','primary')}`);}
function submit(correct,form){const w=state().checkpoint;if(!w||w.feedback)return;w.feedback={correct};if(w.phase!=='guided')p().records['academy.'+current.use.id]=recordAnswer(p().records['academy.'+current.use.id],{correct,form});persist();lesson();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(['home','library','review','about'].includes(a)){window.speechSynthesis?.cancel();({home,library,review,about})[a]();}
 else if(a==='open')open(Number(b.dataset.index));
 else if(a==='preview-listen'){const s=sceneAt(Number(b.dataset.index));say(s.sentence+' '+s.use.meaning);}
 else if(a==='download'){const s=sceneAt(Number(b.dataset.index)),blob=new Blob([illustration(s)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`academy-${s.index+1}-${s.use.id}-${s.object.art}.svg`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 else if(current&&state().checkpoint){const w=state().checkpoint;
 if(a==='listen'){say(current.sentence+'. '+(w.phase==='learn'||w.phase==='guided'?current.use.meaning+' '+current.use.contrast:w.phase==='meaning'?'What does '+current.use.word+' mean here? '+options.map(x=>x.use).join('. '):'Which picture matches? Use Describe picture for a spoken text alternative.'));return;}
 if(a==='compare'){opposite=!opposite;lesson();return;}
 if(a==='teach-next'&&w.phase==='learn'){w.phase='guided';w.feedback=null;choiceOrder=null;}
 else if(a==='reteach'&&!w.feedback){w.phase='learn';choiceOrder=null;}
 else if(a==='answer-picture'&&['guided','picture'].includes(w.phase)){submit(b.dataset.kind===current.use.scene,'context');return;}
 else if(a==='answer-meaning'&&w.phase==='meaning'){submit(b.dataset.id===current.use.id,'meaning');return;}
 else if(a==='continue'&&w.feedback){if(!w.feedback.correct){w.phase='learn';}else{w.phase={guided:'picture',picture:'meaning',meaning:'done'}[w.phase];w.feedback=null;}choiceOrder=null;}
 persist();lesson();
 }
 window.scrollTo({top:0,behavior:'instant'});
});
document.addEventListener('change',e=>{if(e.target.id==='profile'){if('speechSynthesis'in window)speechSynthesis.cancel();save.active=e.target.value;current=null;state();persist();home();}else if(e.target.id==='use'||e.target.id==='object')preview();});
window.addEventListener('storage',e=>{if(e.key===save.key){const latest=loadSave(localStorage);if(!latest.error){save=latest.save;current=null;home();announce('Family progress was updated in another tab. Your saved place is ready.');}}});
// #library, #review and #about open those pages directly (used by Solving English Problems).
(({library,review,about})[location.hash.slice(1)]||home)();
