import {createWordRaidersSync} from './wordraiders-sync.js?v=journey-1';
import {createArcade} from './arcade.js?v=journey-1';
import {recordAnswer,DAY} from './engine.js';
import {loadSave,saveBack} from './wordraiders-save.js';
import {USES,UNITS,OBJECTS,TOTAL,SOURCES,sceneAt,nextIndex,stateFor,checkpoint,canOpen,complete} from './content.js';
import {illustration,describe,escape as esc} from './art.js';
import {startClock,deviceId} from '../journey-shared.js';
const app=document.querySelector('#app'),initial=loadSave(localStorage);let save=initial.save,blocked=!!initial.error,view='home',current=null,opposite=false,options=[],choiceOrder=null;
let arcade,sync;
// Session countdown for a Journey visit (#continue): 5 minutes, as the Today list shows, or ?minutes=N. Counts only while
// the page is visible, and survives a reload in this tab.
const SESSION_KEY='cw-session-left';let session=null;
let SESSION_MIN=5;
function startSession(){const m=Math.max(1,Math.min(60,Number(new URLSearchParams(location.search).get('minutes'))||5));SESSION_MIN=m;session={left:m*60};try{sessionStorage.setItem(SESSION_KEY,String(session.left));}catch{}}
try{const left=Number(sessionStorage.getItem(SESSION_KEY));if(left>0||sessionStorage.getItem(SESSION_KEY)==='0')session={left:Math.max(0,left)};}catch{}
const clockText=()=>session?`⏱ ${Math.floor(session.left/60)}:${String(session.left%60).padStart(2,'0')}`:'';
const timeUp=()=>!!session&&session.left<=0;
setInterval(()=>{if(!session||session.left<=0||document.visibilityState!=='visible')return;session.left--;try{sessionStorage.setItem(SESSION_KEY,String(session.left));}catch{}
 const el=document.querySelector('#focus-timer');if(el){el.textContent=clockText();el.classList.toggle('low',session.left<=60);}
 if(session.left===0){sessionDone();announce('Time’s up — great work!');if(view==='lesson')lesson();}},1000);
// Today's Journey session is done: WordRaiders Home ticks its "5 min" step for this player today (UTC day, as the app counts days).
function sessionDone(){if(!save.player)return;try{localStorage.setItem('wr-today-session',JSON.stringify({day:new Date().toISOString().slice(0,10),name:p().name}));}catch{}}
const p=()=>save.profiles.find(x=>x.id===save.active),state=()=>stateFor(p());
// Pop-up messages clear themselves after a few seconds, so they never sit on top of the answers.
let announceTimer=0;function announce(s){const el=document.querySelector('#status');el.textContent=s;clearTimeout(announceTimer);if(s)announceTimer=setTimeout(()=>{if(el.textContent===s)el.textContent='';},4000);}
function persist(){if(blocked)return false;try{saveBack(localStorage,save);sync?.changed();return true;}catch{blocked=true;announce('Saving is unavailable. Export a backup from WordRaiders settings.');return false;}}
// The voice chosen in WordRaiders Settings, else the best English voice: a downloaded Premium or Enhanced voice first
// (an iPhone says the quality only in the voice id), as src/game/audio.ts rankVoices does.
function voiceFor(){try{const all=speechSynthesis.getVoices().filter(v=>/^en/i.test(v.lang));let name='';try{name=JSON.parse(localStorage.getItem(save.key)||'{}')?.settings?.voice||'';}catch{}
 const q=v=>{const t=v.name+' '+(v.voiceURI||'');return /premium/i.test(t)?8:/enhanced|natural|neural|online/i.test(t)?6:/compact/i.test(t)?-4:0;};
 return all.find(v=>v.name===name&&q(v)>=Math.max(...all.filter(w=>w.name===name).map(q)))||all.sort((a,b)=>q(b)-q(a)+(/en[-_]US/i.test(b.lang)?2:0)-(/en[-_]US/i.test(a.lang)?2:0))[0]||null;}catch{return null;}}
function say(t){if(!('speechSynthesis'in window)){announce('Read-aloud is not available in this browser. All lesson text is on screen.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);const v=voiceFor();u.lang=v?.lang||'en-US';if(v)u.voice=v;u.rate=.82;speechSynthesis.speak(u);}
const btn=(label,action,attrs='',cls='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
function shell(body){const count=Object.keys(state().completed).length;app.innerHTML=`<header><a href="../?journey" class="brand"><span class="brand-icon">a<span>b</span></span><span>SMALL COMMON WORD<b>ACADEMY</b></span></a><div class="profile">${btn('☁ Sync','sync','','primary')}<span>${save.player?'Playing as':'Guest'} <b>${esc(p().name)}</b></span><a href="../?journey">${save.player?'Back to WordRaiders ↗':'Open WordRaiders to save to a player ↗'}</a></div></header><nav aria-label="Academy navigation">${btn('My journey','home','',view==='home'?'active':'')}${btn('Picture library','library','',view==='library'?'active':'')}${btn('Review meanings','review','',view==='review'?'active':'')}${btn('Arcade','arcade','',view==='arcade'?'active':'')}<span>${count.toLocaleString()} / 3,000 scenes</span></nav><main id="main" tabindex="-1">${blocked?'<p class="warning">Progress cannot be saved here. Your existing backup has not been overwritten. Use WordRaiders settings to manage saving.</p>':''}${body}</main><footer><a href="../?journey">← WordRaiders</a><span>Original illustrations • One relationship at a time</span></footer>`;}
// A lesson fills the screen: no header, tabs or footer, only the way back to WordRaiders, the word and the session clock.
function focus(body,label=''){app.innerHTML=`<div class="focus-bar"><a class="focus-back" href="../?journey">← WordRaiders</a><span class="focus-word">${label}</span><span class="focus-timer" id="focus-timer" ${session?'':'hidden'}>${clockText()}</span></div><main id="main" class="focus-main" tabindex="-1">${blocked?'<p class="warning">Progress cannot be saved here. Use WordRaiders settings to manage saving.</p>':''}${timeUp()?`<p class="time-up" role="status">Time’s up — great work! Finish this scene, then head Home.</p>`:''}${body}</main>`;}
function home(){arcade?.leave();view='home';const c=state().completed,n=nextIndex(c),count=Object.keys(c).length,resume=state().checkpoint;
 shell(`<section class="hero"><div><p class="eyebrow">THE LITTLE WORDS. THE BIG PICTURE.</p><h1>See the meaning.<br>Build your foundation.</h1><p>A picture, a clear explanation, and a chance to show what you understand. Your journey has a finish line: <strong>3,000 illustrated scenes.</strong></p><div class="actions">${n!==null?btn(resume?'Continue my journey →':'Start my journey →','open',`data-index="${resume?.index??n}"`,'primary'):btn('Explore my completed academy','library','','primary')}${btn('How this academy works','about')}</div><p class="small">60 common-word uses × 50 pictured contexts. These are 3,000 scenes, not 3,000 different definitions.</p></div><div class="hero-art">${illustration(sceneAt(0))}<span>“in” connects the object to its location.</span></div></section><section class="progress-card"><div><b>${count.toLocaleString()}</b><span>scenes completed</span></div><progress max="3000" value="${count}" aria-label="Academy completion"></progress><strong>${Math.round(count/30)}%</strong></section><div class="section-title"><div><p class="eyebrow">YOUR TEN EXPEDITIONS</p><h2>${n===null?'Your academy journey is complete.':'One small scene at a time.'}</h2></div><span>300 scenes per expedition</span></div><div class="chapters">${Array.from({length:10},(_,r)=>{const done=Array.from({length:300},(_,j)=>!!c['a'+(r*300+j)]).filter(Boolean).length;return `<details ${n!==null&&Math.floor(n/300)===r?'open':''}><summary><span class="chapter-number">${done===300?'✓':r+1}</span><div><h3>${['First discoveries','New objects, familiar meanings','Growing connections','Everyday explorers','Clearer pictures','Meaning detectives','Confident connections','Transfer trail','Deep understanding','The final expedition'][r]}</h3><p>${done} / 300 scenes • ${OBJECTS[r*5].noun} to ${OBJECTS[r*5+4].noun}</p></div><span>⌄</span></summary><div class="units">${UNITS.map(([title,sub],u)=>{let start=r*300+u*50,done=Array.from({length:50},(_,j)=>!!c['a'+(start+j)]).filter(Boolean).length;let index=Array.from({length:50},(_,j)=>start+j).find(i=>!c['a'+i])??start;return `<button data-action="open" data-index="${index}" ${canOpen(p(),index)?'':'disabled'}><span>${done===50?'✓':u+1}</span><div><b>${title}</b><small>${sub}</small><small>${done}/50 scenes</small></div><span>${canOpen(p(),index)?'→':'Locked'}</span></button>`;}).join('')}</div></details>`;}).join('')}</div><p class="note">Each scene includes teaching, guided practice, a picture check, and a meaning check. Completion opens the next scene. Later reviews check retention separately. Progress stays with your WordRaiders player. Use Sync to send your Journey and Arcade progress to your other devices.</p>`);
}
function open(index){if(!canOpen(p(),index)){announce('Finish your current scene to open this one. You can preview every illustration in Picture library.');return;}current=sceneAt(index);if(state().checkpoint?.index!==index)state().checkpoint=checkpoint(index);opposite=false;choiceOrder=null;persist();view='lesson';lesson();}
// A word's scenes come in sets of five (one word, five objects). Once its independent checks are right MASTERY times in a
// row (two scenes with no miss), the rest of the set counts as done: the kid moves on instead of repeating a known word.
const MASTERY=4;
function knowsWord(s){const r=p().records['academy.'+s.use.id];if(!r||r.streak<MASTERY)return false;const c=state().completed,start=s.index-s.index%5,now=Date.now();let skipped=0;
 for(let i=start;i<start+5;i++)if(!c['a'+i]){c['a'+i]=now;skipped++;}return skipped>0;}
function wordProgress(s){const c=state().completed,start=s.index-s.index%5;return `${Array.from({length:5},(_,i)=>c['a'+(start+i)]||start+i===s.index?'●':'○').join('')}`;}
function answerOptions(){if(!choiceOrder){choiceOrder=Math.random()<.5?[current.use.scene,current.use.wrong]:[current.use.wrong,current.use.scene];}return choiceOrder;}
function lesson(){const s=current,w=state().checkpoint;if(!s||!w){home();return;}const u=s.use,phase=w.phase;
 if(phase==='done'){const was=!!state().completed[s.id];complete(p(),s.index);const known=!was&&knowsWord(s);persist();const n=nextIndex(state().completed);
  focus(`<section class="celebration"><div class="medal">✦</div><p class="eyebrow">${known?'WORD LEARNED':(s.index+1)%300===0?'EXPEDITION COMPLETE':'SCENE COMPLETE'}</p><h1>${known?`You know “${esc(u.word)}”!`:'You made the connection.'}</h1><p>${esc(s.sentence)}</p><p>${was?'Review finished. Your completion is preserved.':known?`Right ${MASTERY} times in a row, so its other pictures count as done. On to the next word. +10 XP`:'Both independent checks passed. +10 XP'}</p>${timeUp()?`<p class="time-done">✓ Today’s ${SESSION_MIN} minute${SESSION_MIN===1?'':'s'} ${SESSION_MIN===1?'is':'are'} done!</p><div class="actions"><a class="button primary" href="../?journey&today=next">Next task ▸</a><a class="button" href="../?journey">Back to Home</a>${n!==null?btn('Keep going →','open',`data-index="${n}"`):''}</div>`:`<div class="actions">${n!==null?btn(known?'Next word →':'Next scene →','open',`data-index="${n}"`,'primary'):btn('See my completed journey','home','','primary')}<a class="button" href="../?journey">Back to WordRaiders</a></div>`}</section>`,esc(u.word));return;}
 const feedback=w.feedback;let body='';
 if(phase==='learn'){body=`<div class="lesson-grid"><section class="scene-card">${illustration(s,opposite?u.wrong:u.scene,{caption:!opposite,legend:false})}<p class="caption">${esc(opposite?describe(s,u.wrong):s.sentence)}</p>${btn(opposite?'Show the meaning again':'Compare a different relationship','compare','','quiet')}</section><section class="explanation"><span class="word-tag">${esc(u.word)}</span><h1>${esc(u.use)}</h1><p class="definition">${esc(u.meaning)}</p><div class="notice"><b>Notice the difference</b><p>${esc(u.contrast)}</p></div>${feedback?'<p class="warning">Let’s look again. Read or listen to the explanation, then try with help.</p>':''}<div class="actions">${btn('Read this to me','listen')}${btn('Practice with help →','teach-next','','primary')}</div><p class="small">Say the sentence. Point to the part of the picture that makes it true.</p></section></div>`;
 }else if((phase==='guided'||phase==='picture')&&feedback){body=`<div class="answered"><p class="sentence">${esc(s.sentence)}</p><div class="picture-choice correct answered-pic">${illustration(s,u.scene,{legend:false})}</div></div>`;
 }else if(phase==='guided'||phase==='picture'){const guided=phase==='guided';body=`<div class="prompt"><p class="eyebrow">${guided?'PRACTICE WITH HELP':'INDEPENDENT CHECK 1 OF 2'}</p><h1>Which picture matches?</h1>${btn(`${esc(s.sentence)} <span aria-hidden="true">🔊</span>`,'listen','aria-label="Read the sentence aloud"','sentence say')}${guided?`<p class="hint">${esc(u.meaning)}</p>`:''}</div><div class="picture-options">${answerOptions().map((kind,i)=>`<div><button class="picture-choice ${feedback&&kind===u.scene?'correct':''}" data-action="answer-picture" data-kind="${kind}" ${feedback?'disabled':''} aria-label="Picture ${i+1}: ${esc(describe(s,kind))}"><span class="option-number">${i+1}</span>${illustration(s,kind,{caption:false,legend:false})}</button></div>`).join('')}</div>`;
 }else if(phase==='meaning'&&feedback){body=`<div class="answered"><section class="scene-card">${illustration(s,u.scene,{legend:false})}<p class="caption">${esc(s.sentence)}</p></section><p class="answered-meaning"><b>“${esc(u.word)}” here:</b> ${esc(u.use)}</p></div>`;
 }else if(phase==='meaning'){options=[{id:u.id,use:u.use},{id:'wrong',use:u.incorrect}];if(s.index%2)options.reverse();body=`<div class="meaning-grid"><section class="scene-card">${illustration(s,s.use.scene,{legend:false})}<p class="caption">${esc(s.sentence)}</p></section><section><p class="eyebrow">INDEPENDENT CHECK 2 OF 2</p><h1>${btn(`What does “${esc(u.word)}” mean here? <span aria-hidden="true">🔊</span>`,'listen','aria-label="Read the question aloud"','say')}</h1><div class="meaning-options">${options.map(x=>btn(esc(x.use),'answer-meaning',`data-id="${x.id}" ${feedback?'disabled':''}`,feedback&&x.id===u.id?'correct':'')).join('')}</div></section></div>`;}
 if(feedback&&phase!=='learn')body+=`<section class="feedback ${feedback.correct?'good':'wrong'}" role="status"><b>${feedback.correct?(phase==='guided'?'You found it with help.':'That relationship fits.'):'Let’s make the meaning clearer.'}</b><p>${esc(feedback.correct?u.meaning:u.contrast)}</p>${btn(feedback.correct?'Continue →':'Teach me again →','continue','','primary')}</section>`;
 focus(`<ol class="steps">${[['learn','Learn'],['guided','Together'],['picture','Picture'],['meaning','Meaning']].map(([key,label],i)=>`<li class="${phase===key?'active':''}" ${phase===key?'aria-current="step"':''}>${i+1}. ${label}</li>`).join('')}</ol>${body}`,`${esc(u.word)} <small>${wordProgress(s)}</small>`);
}
function library(){view='library';shell(`<p class="eyebrow">ALL 3,000 SCENES ARE AVAILABLE TO EXPLORE</p><h1>Your illustrated word library.</h1><p>Choose a word use and an object. Each pairing has its own sentence and original illustration. Library previews do not grant completion.</p><div class="filters"><label>Word and meaning<select id="use">${USES.map((u,i)=>`<option value="${i}">${esc(u.word)} — ${esc(u.use)}</option>`).join('')}</select></label><label>Illustrated object<select id="object">${OBJECTS.map((o,i)=>`<option value="${i}">${esc(o.noun)}</option>`).join('')}</select></label></div><div id="library-scene"></div>`);preview();}
function preview(){const ui=Number(document.querySelector('#use').value),oi=Number(document.querySelector('#object').value),index=Math.floor(oi/5)*300+ui*5+oi%5,s=sceneAt(index);document.querySelector('#library-scene').innerHTML=`<div class="lesson-grid"><section class="scene-card">${illustration(s)}<p class="caption">${esc(s.sentence)}</p></section><section class="explanation"><span class="word-tag">${esc(s.use.word)}</span><h2>${esc(s.use.use)}</h2><p>${esc(s.use.meaning)}</p><p>${esc(s.use.contrast)}</p><div class="actions">${btn('Read this scene','preview-listen',`data-index="${index}"`)}${btn('Download illustration','download',`data-index="${index}"`)}${canOpen(p(),index)?btn('Open lesson','open',`data-index="${index}"`,'primary'):''}</div><p class="small">Illustration ${index+1}/3,000 • original SVG diagram</p></section></div>`;}
function review(){view='review';const es=USES.filter(u=>p().records['academy.'+u.id]);shell(`<p class="eyebrow">KEEP THE MEANING WITH YOU</p><h1>Return, remember, reconnect.</h1><p>Scene completion records what you finished. This notebook separately shows answers across days and meanings that need another look.</p><div class="review-list">${es.length?es.map(u=>{let r=p().records['academy.'+u.id],due=r.repair||r.due<=Date.now(),strong=r.days.length>=3&&r.streak>=4&&r.forms.includes('context')&&r.forms.includes('meaning')&&!due;let index=Object.keys(state().completed).map(x=>Number(x.slice(1))).find(i=>sceneAt(i).use.id===u.id);return `<article><span class="word-tag">${esc(u.word)}</span><div><h2>${esc(u.use)}</h2><p>${r.days.length} successful practice dates • ${r.correct}/${r.attempts} independent answers</p><p>${due?'Review due':strong?'Review current across three or more days':'Building evidence over time'}</p></div>${index!==undefined?btn('Review a scene','open',`data-index="${index}"`):btn('Continue learning','open',`data-index="${nextIndex(state().completed)}"`)}</article>`;}).join(''):'<p class="empty">Your first independent answer will start your review notebook.</p>'}</div><p class="note">Review timing uses the game’s 1, 3, 7, 14, 30 and 60-day schedule. These are learning records, not a validated test of vocabulary mastery.</p>`);}
function about(){view='about';shell(`<p class="eyebrow">HOW THE ACADEMY WORKS</p><h1>Small words deserve clear pictures.</h1><p>This academy contains 60 selected uses of common words and phrases. Each appears in 50 object contexts, giving 3,000 distinct illustrated scenes. Multiple contexts practice transfer of a meaning; they are not counted as new dictionary definitions.</p><p>The journey has ten expeditions. Each has six units of 50 scenes. Every scene teaches first, offers guided practice, then checks picture understanding and meaning independently. A miss returns to teaching. All illustrations can be explored freely in Picture library.</p><p>Vector diagrams use boundaries, arrows, group counts, and labels to make relationships visible. Some abstract uses need labels and explanation as well as pictures. Arrows show either movement or pointing, as described in the lesson. Faint objects mark earlier positions.</p><p>This is an original curriculum inspired by the idea of illustrated common-word learning. No illustrations, definitions, or page layouts from Small Common Words Defined have been reproduced. It does not claim to cover all English uses or idioms, or a full school curriculum.</p><h2>Grammar references</h2><ul>${SOURCES.map(([n,url])=>`<li><a href="${url}" target="_blank" rel="noopener">${n}</a></li>`).join('')}</ul><p>Explanations and artwork are original. Profiles and progress are shared with Linguistics Quest on this browser. Use its Profiles screen for creation, renaming, and validated backup export/import.</p>${btn('Start exploring','home','','primary')}`);}
function submit(correct,form){const w=state().checkpoint;if(!w||w.feedback)return;w.feedback={correct};if(w.phase!=='guided')p().records['academy.'+current.use.id]=recordAnswer(p().records['academy.'+current.use.id],{correct,form});persist();lesson();window.scrollTo({top:0,behavior:'instant'});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a!=='arcade'&&a!=='sync')arcade?.leave();
 if(a==='sync')return;
 if(a==='arcade'){arcade.open();return;}
 if(['home','library','review','about'].includes(a)){window.speechSynthesis?.cancel();({home,library,review,about})[a]();}
 else if(a==='open')open(Number(b.dataset.index));
 else if(a==='preview-listen'){const s=sceneAt(Number(b.dataset.index));say(s.sentence+' '+s.use.meaning);}
 else if(a==='download'){const s=sceneAt(Number(b.dataset.index)),blob=new Blob([illustration(s)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`academy-${s.index+1}-${s.use.id}-${s.object.art}.svg`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 else if(current&&state().checkpoint){const w=state().checkpoint;
 if(a==='listen'){say(current.sentence+'. '+(w.phase==='learn'||w.phase==='guided'?current.use.meaning+' '+current.use.contrast:w.phase==='meaning'?'What does '+current.use.word+' mean here? '+options.map(x=>x.use).join('. '):'Which picture matches? '+answerOptions().map((k,i)=>'Picture '+(i+1)+': '+describe(current,k)).join(' ')));return;}
 if(a==='compare'){opposite=!opposite;lesson();return;}
 if(a==='teach-next'&&w.phase==='learn'){w.phase='guided';w.feedback=null;choiceOrder=null;}
 else if(a==='reteach'&&!w.feedback){w.phase='learn';choiceOrder=null;}
 else if(a==='answer-picture'&&['guided','picture'].includes(w.phase)){submit(b.dataset.kind===current.use.scene,'context');return;}
 else if(a==='answer-meaning'&&w.phase==='meaning'){submit(b.dataset.id===current.use.id,'meaning');return;}
 else if(a==='continue'&&w.feedback){if(!w.feedback.correct){w.phase='learn';}else{w.phase={guided:'picture',picture:'meaning',meaning:'done'}[w.phase];w.feedback=null;}choiceOrder=null;}
 persist();lesson();
 }
 window.scrollTo({top:0,behavior:'instant'});
});
document.addEventListener('change',e=>{if(e.target.id==='profile'){if('speechSynthesis'in window)speechSynthesis.cancel();save.active=e.target.value;current=null;arcade?.leave();state();persist();home();}else if(e.target.id==='use'||e.target.id==='object')preview();});
window.addEventListener('storage',e=>{if(e.key===save.key){const latest=loadSave(localStorage);if(!latest.error){save=latest.save;current=null;home();announce('Family progress was updated in another tab. Your saved place is ready.');}}});
// #library, #review and #about open those pages directly (used by Solving English Problems).
arcade=createArcade({profile:p,persist,shell:body=>{view='arcade';shell(body);},speak:say,announce,journey:home});
(({library,review,about,arcade:()=>arcade.open()})[location.hash.slice(1)]||home)();

// Journey time: count active minutes for a real WordRaiders player (never the guest) and say once when today's budget
// is reached. The clock writes only its own device-local key (docs/unified-journey.md §4).
let clock=null,clockFor='';
function journeyRaw(){try{const raw=JSON.parse(localStorage.getItem(save.key)||'{}');return raw&&typeof raw.journey==='object'&&!Array.isArray(raw.journey)?raw.journey:null;}catch{return null;}}
function budgetLeft(day){const j=journeyRaw();if(!j)return Infinity;const minutes=Number(j.budget)>0?Number(j.budget):60,device=deviceId(localStorage),today=j.time&&typeof j.time==='object'?j.time[day]:null;let others=0;if(today&&typeof today==='object')for(const [d,sec] of Object.entries(today))if(d!==device&&Number.isFinite(sec))others+=sec;return minutes*60-others;}
function runClock(){const id=save.player?save.active:'';if(id===clockFor)return;clock?.stop();clock=null;clockFor=id;if(!id)return;
 try{clock=startClock({playerId:id,surface:'common-words',budgetSeconds:budgetLeft,onBudget:()=>{const msg='Today’s Journey time is done — a good place to stop';announce(msg);setTimeout(()=>{if(document.querySelector('#status').textContent===msg)announce('');},8000);}});}catch{clock=null;}}
runClock();
// #continue (from the WordRaiders Journey) opens the next scene, exactly like the Continue button on My journey.
if(location.hash==='#continue'){startSession();const n=nextIndex(state().completed),resume=state().checkpoint,index=resume?.index??n;if(index!==null&&index!==undefined)open(index);history.replaceState(null,'',location.pathname+location.search);}
sync=createWordRaidersSync({getSave:()=>save,persist,isBlocked:()=>blocked,applySave:next=>{save=next;arcade?.leave();home();runClock();}});
sync.start();
