import {USES,OBJECTS,sceneAt} from './content.js';
import {illustration,describe,escape as esc} from './art.js';
import {SENTENCE_COUNT,sceneIndex} from './arcade-bank.js';
import {LANES,MODES,state,useState,unlocked,useUnlocked,nextQuestion,record,mastery} from './arcade-model.js';
let artSerial=0;
export function arcadeArt(s,kind){const id='arc-tip-'+(++artSerial);return illustration(s,kind,{caption:false}).replaceAll('id="tip"',`id="${id}"`).replaceAll('url(#tip)',`url(#${id})`).replace('same object → it','same object').replace('A BOOK ABOUT','BOOK TOPIC').replace('PACKED BY ','PACKED: ').replace('>OR<','>CHOOSE ONE<');}
const button=(s,a,attrs='',cls='')=>`<button class="${cls}" data-arcade="${a}" ${attrs}>${s}</button>`;
const fmt=t=>Math.max(0,Math.ceil(t/1000))+'s';
export function createArcade({profile,persist,shell,speak,announce,journey}){
 let lane=0,mode='Practice',duration=60,size=10,selection=-1,format='rotate',run=null,timer=null,screen='hub';
 function save(){return persist();}
 function render(body){shell(`<section class="word-arcade">${body}</section>`);}
 function available(){return unlocked(profile(),lane);}
 function hub(){clearInterval(timer);timer=null;screen='hub';const pool=available(),a=state(profile());if(selection!==-1&&!pool.includes(selection))selection=-1;
 render(`<div class="arc-hero"><div><p class="eyebrow">THE ARCADE · BUILD UNDERSTANDING</p><h1>Common Word Arcade</h1><p>Word gym · picture meanings · blitz</p><p class="arc-sub">${SENTENCE_COUNT.toLocaleString()} illustrated sentence combinations + 120 everyday situations. Journey teaches; this is where you practice.</p></div><div class="arc-emblem" aria-hidden="true">a<span>↔</span>b</div></div><div class="arc-stations" aria-label="Signature stations">${button('⚒ Scene Forge<br><small>Build and repair · 5 challenges</small>','station','data-station="forge"')}${button('▧ Picture Match Arena<br><small>10-picture ladder</small>','station','data-station="arena"')}${button('✦ Meaning Millionaire<br><small>15 steps · helpful lifelines</small>','station','data-station="millionaire"')}</div>
 <div class="arc-tabs" role="tablist" aria-label="Practice skill">${LANES.map((name,i)=>button(esc(name)+(unlocked(profile(),i).length?'':' 🔒'),'lane',`data-lane="${i}" role="tab" aria-selected="${i===lane}"`,i===lane?'selected':'')).join('')}</div>
 <div class="arc-setup" role="tabpanel" aria-label="Selected practice skill"><h2>${LANES[lane]}</h2><p class="note">Each meaning opens after its first five Journey scenes, including their independent checks. Journey drills open immediately for scenes you have completed.</p>${pool.length?`<div class="arc-controls"><label>Meaning<select id="arc-use"><option value="-1">All available meanings (${pool.length})</option>${pool.map(i=>`<option value="${i}" ${selection===i?'selected':''}>${esc(USES[i].word)} — ${esc(USES[i].use)}</option>`).join('')}</select></label><label>Question bank<select id="arc-format">${[['rotate','Varied workout'],['transfer','Everyday situations'],['recall','Recall the word'],['picture','Picture matching']].map(([id,label])=>`<option value="${id}" ${format===id?'selected':''}>${label}</option>`).join('')}</select></label></div><div class="arc-modes" role="group" aria-label="Session mode">${MODES.map(m=>button(m,'mode',`data-mode="${m}" aria-pressed="${mode===m}"`,mode===m?'selected':'')).join('')}</div><p>${{Practice:'Untimed. Learn from feedback, ask for a hint, and stop whenever you like.',Blitz:'A timed workout. Speed records do not certify mastery.',Speed:'A fixed set with a clock for each question. Correctness comes first.',Conquer:'Clear 50 objects for one meaning. Misses return. Progress is saved between visits.'}[mode]}</p>${mode==='Blitz'?`<label>Run length<select id="arc-duration">${[30,60,90].map(n=>`<option ${duration===n?'selected':''}>${n}</option>`).join('')}</select> seconds</label>`:''}${mode==='Speed'?`<label>Number of questions<select id="arc-size">${[10,20].map(n=>`<option ${size===n?'selected':''}>${n}</option>`).join('')}</select></label><p>${a.speed} seconds per item. The clock tightens only after at least 90% correct and on time.</p>`:''}${mode==='Conquer'&&selection===-1?'<p>Choose one meaning above to start Conquer.</p>':''}${button('Play '+mode,'start',mode==='Conquer'&&selection===-1?'disabled':'','primary')}`:`<div class="arc-empty"><h3>${lane===8?'No reviews due here yet.':'Learn a little, then play.'}</h3><p>${lane===7?'Finish your first scene to practice it here.':lane===8?'Try another skill or return after a day for a review.':'Finish five introductory scenes for a meaning to open it here. You do not need to finish all 500 scenes in a unit.'}</p>${button('Continue Journey →','journey','','primary')}</div>`}</div>
 <details class="arc-rules"><summary>How 100% mastery works</summary><p>For each meaning: answer independently across all 50 objects, five practice sentence patterns and five question types; answer both everyday situations; practice correctly on three different dates; then pass a 20-question check at 100% using the reserved sixth sentence pattern. Your latest 20 answers must also all be correct, unassisted and distinct.</p><p>Hints never count as independent mastery. A miss creates a new practice target. Crowns and speed records are separate achievements. These are transparent game criteria, not a standardized language assessment.</p></details>
 <div class="arc-progress"><h2>Meaning by meaning</h2>${pool.map(i=>{const m=mastery(profile(),i),u=USES[i],c=a.crowns[u.id];return `<article><div><h3>${esc(u.word)} <small>${esc(u.use)}</small></h3><p>${m.mastered?'✓ Mastered at 100%':`${m.percent}% of mastery requirements met`} ${c?' · ♛ Conquer crown':''}</p><progress max="6" value="${m.percent===100?6:Math.round(m.percent/100*6)}" aria-label="${esc(u.word)} mastery requirements"></progress><p class="note">${m.objects}/50 objects · ${m.patterns}/5 patterns · ${m.types}/5 types · ${m.transfers}/2 situations · ${Math.min(3,m.days)}/3 dates</p></div>${button('Mastery check','check',`data-use="${i}" ${m.ready?'':'disabled'}`)}</article>`;}).join('')||'<p>Completed Journey meanings will appear here.</p>'}</div><details><summary>Best scores and station stars</summary>${Object.entries(a.bests).map(([key,v])=>`<p>${esc(key)}: ${v.score} points ${v.pass?'★':''}</p>`).join('')||'<p>Your first completed run starts your record.</p>'}</details>`);
 }
 function start(station=null,checkUse=null){
  const pool=available();if(!pool.length){announce('Complete introductory Journey scenes first.');return;}
  if(checkUse!==null&&!mastery(profile(),checkUse).ready){announce('Finish the practice requirements before the mastery check.');return;}
  if(mode==='Conquer'&&!station&&checkUse===null&&selection===-1){announce('Choose one meaning for Conquer.');return;}
  const target=checkUse!==null?checkUse:selection===-1?null:selection;
  if(target!==null&&!pool.includes(target))return;
  const actual=checkUse!==null?'Check':station?'Station':mode;
  run={mode:actual,station,target,serial:0,correct:0,attempts:0,score:0,combo:0,bestCombo:0,hinted:false,answered:false,choice:null,started:Date.now(),deadline:actual==='Blitz'?Date.now()+duration*1000:0,limit:checkUse!==null?20:station==='forge'?5:station==='arena'?10:station==='millionaire'?15:actual==='Speed'?size:Infinity,clean:0,lifelines:new Set(),hiddenChoices:[],paused:false};
  if(actual==='Conquer'){const id=USES[target].id;const progress=state(profile()).conquer[id]||{at:Date.now(),cleared:[],elapsed:0};if(progress.cleared.length===50){progress.cleared=[];progress.elapsed=0;}state(profile()).conquer[id]=progress;run.queue=OBJECTS.map(o=>o.id).filter(id=>!progress.cleared.includes(id));}
  screen='run';next();
 }
 function next(){if(!run)return;if(run.attempts>=run.limit||(run.mode==='Conquer'&&!run.queue.length)||(run.deadline&&Date.now()>=run.deadline)){finish();return;}
  const opts={use:run.target,assessment:run.mode==='Check'};
  if(run.mode==='Conquer'){opts.object=run.queue.shift();opts.kind='picture';}
  else if(run.station==='forge')opts.kind='swap';
  else if(run.station==='arena')opts.kind='picture';
  else if(run.station==='millionaire')opts.kind=run.serial<5?'meaning':run.serial<10?'swap':'transfer';
  else if(run.mode!=='Check'&&format!=='rotate')opts.kind=format;
  if(lane===7&&opts.kind==='transfer')opts.kind='picture';
  run.q=nextQuestion(profile(),lane,run.serial++,opts);if(!run.q){finish();return;}
  if(run.station==='millionaire'&&run.q.choices?.every(c=>c.label)){run.q.choices.push({label:'The situation does not provide enough information.',correct:false},{label:'Both choices have exactly the same meaning here.',correct:false});}
  run.hinted=false;run.hintShown=false;run.answered=false;run.choice=null;run.hiddenChoices=[];run.qStarted=Date.now();save();play();clearInterval(timer);timer=setInterval(tick,200);
 }
 function tick(){if(!run||screen!=='run')return;if(run.deadline&&Date.now()>=run.deadline){finish();return;}const el=document.querySelector('#arc-clock');if(el)el.textContent=run.mode==='Blitz'?fmt(run.deadline-Date.now()):run.mode==='Speed'?fmt(state(profile()).speed*1000-(Date.now()-run.qStarted)):'No timer';if(run.mode==='Speed'&&!run.answered&&Date.now()-run.qStarted>=state(profile()).speed*1000)answer(-1,true);}
 function lifeline(kind){if(!run||run.answered||run.mode==='Check'||['Blitz','Speed','Conquer'].includes(run.mode))return;
  if(run.station&&run.lifelines.has(kind))return;if(run.station)run.lifelines.add(kind);run.hinted=true;
  if(kind==='skip'){answer(-1);return;}
  if(kind==='hint')run.hintShown=true;
  if(kind==='half'){const wrong=run.q.choices?.map((c,i)=>!c.correct?i:-1).filter(i=>i>=0)||[];run.hiddenChoices=wrong.slice(0,Math.max(0,wrong.length-1));}
  play();
 }
 function play(){const r=run;if(!r)return;const q=r.q;const prefix=r.station?{forge:'Scene Forge',arena:'Picture Match Arena',millionaire:'Meaning Millionaire'}[r.station]:r.mode==='Check'?'Mastery check':r.mode;
 render(`<div class="arc-run-head"><div><p class="eyebrow">${prefix} · ${LANES[lane]}</p><h2>${r.mode==='Conquer'?`${state(profile()).conquer[USES[r.target].id].cleared.length}/50 objects cleared`:r.limit!==Infinity?`Question ${Math.min(r.attempts+1,r.limit)} of ${r.limit}`:'Keep building understanding'}</h2></div>${button('Save & exit','exit')}</div><div class="arc-score"><span>${r.score} points</span><span>${r.correct}/${r.attempts} correct</span><span>Streak ${r.combo}</span><span id="arc-clock" role="timer">${r.mode==='Blitz'?fmt(r.deadline-Date.now()):r.mode==='Speed'?state(profile()).speed+'s':'No timer'}</span></div><div class="arc-question"><p class="eyebrow">${q.kind==='transfer'?'A NEW EVERYDAY SITUATION':q.kind==='recall'?'RECALL THE MEANING':'READ · NOTICE · DECIDE'}</p><h2 id="arc-prompt">${esc(q.prompt)}</h2>${q.text?`<p class="arc-sentence">${esc(q.text)}</p>`:''}${q.clue?`<p class="arc-sentence">${esc(q.clue)}</p>`:''}${button('Listen','listen','','arc-listen')}${q.draw?`<div class="arc-reference">${arcadeArt(q.scene,r.station==='forge'&&r.choice!==null?q.choices[r.choice].draw:q.draw)}</div>`:''}
 ${q.recall?`<form id="arc-recall"><label for="arc-response">Your word or phrase</label><input id="arc-response" autocomplete="off" autocapitalize="none" spellcheck="false" ${r.answered?'disabled':''}><button ${r.answered?'disabled':''}>Check answer</button></form>`:`<div class="arc-answers ${q.choices.length>2?'four':''}" role="group" aria-labelledby="arc-prompt">${q.choices.map((c,i)=>r.hiddenChoices.includes(i)?'':button(`${c.draw?arcadeArt(q.scene,c.draw):`<span>${esc(c.label)}</span>`}${c.draw?`<small>Picture ${i+1}</small>`:''}`,'answer',`data-choice="${i}" ${r.answered?'disabled':''} ${r.station==='forge'?`aria-pressed="${r.choice===i}"`:''}`,r.answered?(c.correct?'arc-correct':r.choice===i?'arc-wrong':''):r.station==='forge'&&r.choice===i?'selected':'')).join('')}</div>`}
 ${r.station==='forge'&&!r.answered?button('Check my repaired scene','forge-check',r.choice===null?'disabled':'','primary'):''}
 <details class="arc-descriptions"><summary>Describe the pictures</summary>${q.draw?`<p>${esc(describe(q.scene,q.draw))}</p>`:''}${q.choices?.filter(c=>c.draw).map((c,i)=>`<p>Picture ${i+1}: ${esc(describe(q.scene,c.draw))}</p>`).join('')||''}<p class="note">Text descriptions explain the visible relationships. They do not identify a correct option.</p></details>
 ${!r.answered&&(r.mode==='Practice'||r.station)?`<div class="arc-lifelines">${button(r.station?'Ask the Journey coach':'Show a hint','hint',r.station&&r.lifelines.has('hint')?'disabled':'')}${r.station?button('Skip this item','skip',r.lifelines.has('skip')?'disabled':''):''}${r.station==='millionaire'?button('50/50','half',r.lifelines.has('half')||!q.choices?.every(c=>c.label)?'disabled':''):''}</div>`:''}
 ${r.hintShown?`<aside class="arc-hint"><b>Supported practice — no independent mastery credit for this answer.</b><p>${esc(q.explanation)}</p>${arcadeArt(q.scene,q.scene.use.scene)}</aside>`:''}
 ${r.answered?`<div class="arc-feedback ${r.lastCorrect?'good':'repair'}" role="status"><h3>${r.lastCorrect?(r.hinted?'Correct with support.':'Correct — independently!'):'Let’s repair that meaning.'}</h3><p><b>${esc(q.scene.use.word)}</b>: ${esc(q.scene.use.meaning)}</p><p>${esc(q.scene.use.contrast)}</p>${q.kind==='transfer'?`<p>Answer: ${esc(q.choices.find(c=>c.correct).label)}</p>`:q.recall?`<p>Answer: ${esc(q.answer)}</p>`:''}${button('Next →','next','','primary')}</div>`:''}</div>`);
 if(q.recall&&!r.answered)document.querySelector('#arc-response')?.focus({preventScroll:true});
 }
 function answer(choice,late=false){const r=run;if(!r||r.answered)return;if(r.deadline&&Date.now()>=r.deadline){finish();return;}
 const q=r.q;r.choice=typeof choice==='number'?choice:null;
 const normalized=String(choice).trim().toLowerCase().replace(/[.!?]+$/,'');
 const correct=!late&&(q.recall?[q.answer,...q.aliases].map(s=>s.toLowerCase()).includes(normalized):q.choices[choice]?.correct===true);
 r.answered=true;r.lastCorrect=correct;r.attempts++;if(correct)r.correct++;r.combo=correct&&!r.hinted?r.combo+1:0;r.bestCombo=Math.max(r.bestCombo,r.combo);
 const clean=record(profile(),q,{correct,hinted:r.hinted});if(clean){r.clean++;r.score+=10+Math.min(20,r.combo*2);}
 if(r.mode==='Conquer'){const c=state(profile()).conquer[USES[r.target].id];c.at=Date.now();c.elapsed+=Date.now()-r.qStarted;if(clean&&!c.cleared.includes(q.o))c.cleared.push(q.o);else if(!clean)r.queue.push(q.o);}
 save();play();
 }
 function finish(){clearInterval(timer);timer=null;if(!run){hub();return;}const r=run,a=state(profile()),seconds=Math.round((Date.now()-r.started)/1000),key=(r.station||r.mode)+'-'+lane+'-'+(r.target??'mixed')+(r.mode==='Blitz'?'-'+duration:r.mode==='Speed'?'-'+size:'');
 const pass=r.attempts>0&&r.clean===r.attempts&&r.attempts>=r.limit;
 if(r.mode==='Check')a.checks[USES[r.target].id]={at:Date.now(),score:r.clean,total:r.attempts,pass:r.attempts===20&&r.clean===20};
 if(r.mode==='Conquer'&&a.conquer[USES[r.target].id].cleared.length===50)a.crowns[USES[r.target].id]={at:Date.now(),score:50,total:50,seconds:a.conquer[USES[r.target].id].elapsed/1000,pass:true};
 if(r.mode==='Speed'&&r.attempts===r.limit&&r.clean/r.limit>=.9)a.speed=Math.max(6,a.speed-2);
 if(!a.bests[key]||r.score>a.bests[key].score)a.bests[key]={at:Date.now(),score:r.score,total:r.attempts,seconds,pass};save();screen='results';run=null;
 render(`<div class="arc-results"><p class="eyebrow">${r.station||r.mode} · RUN SAVED</p><h1>${r.mode==='Check'?(pass?'100% — check passed!':'Keep practicing this meaning.'):r.mode==='Conquer'&&a.conquer[USES[r.target].id].cleared.length===50?'♛ Set conquered!':r.station&&pass?'★ Station cleared!':'Your workout is saved.'}</h1><p class="arc-big">${r.score} points</p><div class="arc-score"><span>${r.correct}/${r.attempts} correct</span><span>${r.clean} unassisted</span><span>${r.bestCombo} best streak</span></div><p>${r.mode==='Check'?'A passed check joins your coverage and spaced practice evidence. A miss means practice and try a fresh check.':'Scores show this run. Mastery separately requires coverage, independent accuracy and later review.'}</p>${button('Back to Arcade','hub','','primary')}${button('Continue Journey','journey')}</div>`);
 }
 function leave(){clearInterval(timer);timer=null;if(run){save();run=null;}screen='away';}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-arcade]');if(!b||b.disabled)return;const a=b.dataset.arcade;
 if(a==='lane'){lane=Number(b.dataset.lane);selection=-1;hub();}else if(a==='mode'){mode=b.dataset.mode;hub();}else if(a==='start')start();else if(a==='station')start(b.dataset.station);else if(a==='check')start(null,Number(b.dataset.use));else if(a==='journey'){leave();journey();}else if(a==='hub')hub();else if(a==='exit')finish();else if(a==='answer'){if(run?.station==='forge'){run.choice=Number(b.dataset.choice);play();}else answer(Number(b.dataset.choice));}else if(a==='forge-check')answer(run.choice);else if(a==='next')next();else if(['hint','skip','half'].includes(a))lifeline(a);else if(a==='listen'&&run){speak([run.q.prompt,run.q.text,run.q.clue].filter(Boolean).join(' '));}
 });
 document.addEventListener('change',e=>{const id=e.target.id;if(id==='arc-use')selection=Number(e.target.value);else if(id==='arc-format')format=e.target.value;else if(id==='arc-duration')duration=Number(e.target.value);else if(id==='arc-size')size=Number(e.target.value);else return;hub();});
 document.addEventListener('submit',e=>{if(e.target.id==='arc-recall'){e.preventDefault();answer(document.querySelector('#arc-response').value);}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&run)save();if(!document.hidden)tick();});
 return {open:hub,leave};
}
