// Original instructional text and scene specifications. No book text or artwork is reproduced.
export const SOURCES=[['Place words','https://dictionary.cambridge.org/grammar/british-grammar/at-on-and-in-place'],['Articles','https://learnenglish.britishcouncil.org/free-resources/grammar/a1-a2-grammar/articles-a-an-the'],['Word classes','https://dictionary.cambridge.org/us/grammar/british-grammar/word-classes-and-phrase-classes'],['Quantifiers','https://dictionary.cambridge.org/grammar/british-grammar/all']];
// Every context has a different named object and a distinct drawing. All are countable, movable objects.
export const OBJECTS=[
 ['ball','balls','ball'],['block','blocks','block'],['coin','coins','coin'],['button','buttons','button'],['marble','marbles','marble'],
 ['pencil','pencils','pencil'],['crayon','crayons','crayon'],['eraser','erasers','eraser'],['book','books','book'],['notebook','notebooks','notebook'],
 ['apple','apples','apple'],['orange','oranges','orange'],['pear','pears','pear'],['banana','bananas','banana'],['carrot','carrots','carrot'],
 ['spoon','spoons','spoon'],['fork','forks','fork'],['cup','cups','cup'],['bottle','bottles','bottle'],['plate','plates','plate'],
 ['sock','socks','sock'],['hat','hats','hat'],['shoe','shoes','shoe'],['glove','gloves','glove'],['scarf','scarves','scarf'],
 ['key','keys','key'],['comb','combs','comb'],['brush','brushes','brush'],['bell','bells','bell'],['candle','candles','candle'],
 ['shell','shells','shell'],['stone','stones','stone'],['leaf','leaves','leaf'],['acorn','acorns','acorn'],['pine cone','pine cones','pinecone'],
 ['toy car','toy cars','car'],['toy boat','toy boats','boat'],['toy rocket','toy rockets','rocket'],['toy train','toy trains','train'],['toy robot','toy robots','robot'],
 ['envelope','envelopes','envelope'],['ticket','tickets','ticket'],['ribbon','ribbons','ribbon'],['ring','rings','ring'],['bead','beads','bead'],
 ['dice cup','dice cups','dicecup'],['puzzle piece','puzzle pieces','puzzle'],['ruler','rulers','ruler'],['feather','feathers','feather'],['toy drum','toy drums','drum']
].map(([noun,plural,art],id)=>({id,noun,plural,art,article:/^[aeiou]/.test(noun)?'an':'a'}));
export const UNITS=[['Place explorers','Find where things are.'],['Path finders','Follow movement and direction.'],['Word pointers','Understand which thing we mean.'],['Connections','Join, include, and exclude.'],['Groups & amounts','Look closely at how much and how many.'],['Time & relationships','Connect events, people, and things.']];
// id, word, specific use, explanation, comparison, scene renderer, contrast renderer, sentence template.
const rows=[
 ['in','in','inside a space','In places something within a space or container. Find the edges of the box, then look inside them.','Beside means next to the box; in means inside it.','in','beside','The {n} is in the box.'],
 ['on','on','resting on a surface','On tells us that something touches and rests on a surface. The shelf is holding the object up.','Above can leave a gap. On touches the supporting surface.','on','above','The {n} is on the shelf.'],
 ['under','under','lower than, beneath','Under puts something lower than another thing. Here the shelf is directly above the object.','An object on the shelf rests on top. Under puts it beneath the shelf.','under','on','The {n} is under the shelf.'],
 ['above','above','higher than','Above means at a higher position. Here there is a gap between the object and the shelf.','Above does not require touching. Below puts it lower.','above','under','The {n} is above the shelf.'],
 ['below','below','at a lower level','Below compares heights. The object is at a lower level than the shelf.','Below and under can overlap in meaning. Above reverses the height relationship.','under','above','The {n} is below the shelf.'],
 ['beside','beside','next to','Beside places something next to another thing. Look to the side of the box.','Inside puts the object within the box instead.','beside','in','The {n} is beside the box.'],
 ['between','between','in the separating space','Between places something in the space separating the two boxes. There is a box on each side.','Being outside both boxes on the same side does not fit this picture of between.','between','beyond','The {n} is between the boxes.'],
 ['outside','outside','not inside a boundary','Outside places something beyond the edges of a container or space. The box does not surround it.','Inside places it within the boundary.','beside','in','The {n} is outside the box.'],
 ['near','near','a short distance away','Near means a short distance away in the situation. Compare the small gap with the larger gap in the other picture.','Near is relative: the situation tells us what distance counts as close.','near','far','The {n} is near the box.'],
 ['far','far from','a large distance away','Far from means a large distance away in this situation. The picture compares a larger gap with a smaller one.','Far is about distance here, not the size of the object.','far','near','The {n} is far from the box.'],
 ['to','to','destination','To points to a destination: where something is going. Follow the arrow to its ending.','From names where the movement starts.','to','from','Move the {n} to the box.'],
 ['from','from','starting place','From identifies a starting place. The faint object marks where the movement began.','To identifies the destination. Start and finish do different jobs.','from','to','Move the {n} from the box.'],
 ['into','into','movement to the inside','Into combines movement with an inside destination. The object starts outside and ends inside.','In can describe a location without telling us that anything moved. Out of reverses this movement.','into','out','Move the {n} into the box.'],
 ['out','out of','movement to the outside','Out of means moving from an inside position to an outside position.','Into goes the other way: outside to inside.','out','into','Move the {n} out of the box.'],
 ['onto','onto','movement to a surface','Onto means moving to a position on a surface. The final object rests on the shelf.','Off moves away from that surface.','onto','off','Move the {n} onto the shelf.'],
 ['off','off','away from a surface','Off means leaving a surface in this use. The starting object was resting on the shelf.','Onto ends on the surface instead.','off','onto','Move the {n} off the shelf.'],
 ['up','up','toward a higher position','Up describes movement toward a higher place. Follow the arrow from the faint starting position.','Down moves toward a lower place.','up','down','Move the {n} up.'],
 ['down','down','toward a lower position','Down describes movement toward a lower place. The ending is lower than the starting position.','Up reverses the direction.','down','up','Move the {n} down.'],
 ['through','through','enter and leave by another opening','Through means entering a passage, moving inside it, and leaving by another opening. Follow the route through the tunnel.','Around follows the outside without entering the tunnel.','through','around','Move the {n} through the tunnel.'],
 ['around','around','following the outside','Around can describe a route along the outside of an obstacle. The arrow curves past the tunnel without entering it.','Through goes inside the passage.','around','through','Move the {n} around the tunnel.'],
 ['a','a','one, not identified in advance','A introduces one thing without identifying a particular one. In this request, either matching object would do. A comes before a consonant sound.','The asks us to identify the particular object meant. A and an do the same job with different following sounds.','any','specific','Please choose a small {n}.'],
 ['an','an','one, before a vowel sound','An introduces one thing without identifying which one. An comes before a vowel sound. In an orange-colored object, orange begins with a vowel sound.','The next sound matters, even when an adjective comes before the noun. An orange-colored ball; a small ball.','anyOrange','specificOrange','Please choose an orange-colored {n}.'],
 ['the','the','an identifiable thing','The points to something the listener can identify. The arrow singles out the particular object in this request.','A could mean either matching object. The object marked by the arrow identifies one.','specific','any','Please choose the {n} marked by the arrow.'],
 ['this','this','one nearby thing','This can point to one thing near the speaker. Use the speaker position as your reference point.','That points farther away in this scene.','this','that','This {n} is near me.'],
 ['that','that','one farther-away thing','That can point to one thing farther from the speaker. Notice which object the speaker indicates.','This points nearby in this scene.','that','this','That {n} is over there.'],
 ['these','these','more than one nearby','These can point to several things near the speaker. It combines a nearby reference with more than one.','Those points to the farther group in this scene.','these','those','These {p} are near me.'],
 ['those','those','more than one farther away','Those can point to several things farther from the speaker. Look for the indicated distant group.','These points to the nearby group in this scene.','those','these','Those {p} are over there.'],
 ['it','it','referring back to a thing','It lets us refer to a thing already mentioned. Here it refers to the named object, so we do not need to repeat the noun.','It does not name a new object here. Follow the reference back to the noun.','reference','referenceWrong','Here is {article} {n}. It is in the box.'],
 ['its','its','belonging to a thing','Its can show that something belongs to, or is associated with, a thing. Here the toy belongs to the robot in our story.','Its shows this relationship. It’s with an apostrophe means it is or it has.','owner','otherOwner','The robot has {article} {n}. Its {n} is in the box.'],
 ['at','at','a location treated as a point','At can identify a location as a point. Here the station is the marked place where the object is waiting.','At does not specify inside or on top. The marked station is what matters here.','at','farStation','The {n} is at the packing station.'],
 ['and','and','including both','And joins the two items. A request for the object and the box includes both.','In our choose-one task, or offers alternatives. And includes both named items.','and','or','Choose the {n} and the box.'],
 ['or','or','offering alternatives','Or offers alternatives here. The instruction says choose one, so either option can satisfy it.','Or can allow both in other situations. Read the full instruction; this one explicitly says choose one.','or','and','Choose one: the {n} or the box.'],
 ['not','not','making a statement negative','Not changes this positive statement into a negative one. The object is outside, so it is not in the box.','Not in excludes inside. It does not tell us exactly where outside the object is.','beside','in','The {n} is not in the box.'],
 ['with','with','together or accompanied by','With links things that are together here. Both named items are in the packing group.','Without excludes the second item from the packing group.','with','without','Pack the {n} with the box.'],
 ['without','without','not accompanied by','Without means the other item is absent from this group. The object is included, but the box is not.','With would include the box in the group.','without','with','Pack the {n} without the box.'],
 ['for','for','intended recipient','For can name who is meant to receive something. Here the package is intended for the person named on the tag.','From would name the sender instead of the intended recipient.','recipient','sender','This {n} is for Maya.'],
 ['by','by','person doing an action','By can tell us who did an action in a passive sentence. Here Maya did the packing.','This does not mean Maya is the recipient. By identifies the person who packed it.','agent','otherAgent','The {n} was packed by Maya.'],
 ['ofContents','of','contents of a container','Of connects a container with what it contains in this use. The boxes hold the named objects.','Of has other jobs. Here ask: what is in the box?','contents','empty','This is a box of {p}.'],
 ['ofPicture','of','what an image represents','Of connects a picture to what it shows. The frame contains a drawing of the named object.','A picture of an object is a representation; it is not the physical object itself.','picture','plain','This is a picture of {article} {n}.'],
 ['about','about','subject of a message','About can name the subject of a message or book. The book here gives information on the named objects.','About tells the topic here, not where the book is located.','topic','otherTopic','This book is about {p}.'],
 ['all','all','the whole group','All includes the entire group we are talking about. Every one of these six objects is inside.','Leaving one outside would fail the claim that all six are inside.','all','some','All six {p} are in the box.'],
 ['some','some','an unspecified positive number','Some can refer to an unspecified positive number. Here three of the six are inside.','Some does not give an exact count. It often suggests not all, but it does not always exclude all. None means zero.','some','none','Some of the {p} are in the box.'],
 ['none','none','zero from the group','None means not one from the named group. The box holds zero of these objects.','An empty box can make this statement true even though objects exist outside it.','none','some','None of the {p} are in the box.'],
 ['both','both','the whole pair','Both includes the two members of a pair. Look for two out of two, not one out of two.','Both refers to two. All can refer to a larger group too.','both','onePair','Both {p} are in the box.'],
 ['each','each','members considered individually','Each directs attention to individual members of a group. Each object gets its own dot in this scene.','Giving a dot to only one member would not satisfy each.','each','oneDot','Put a dot beside each {n}.'],
 ['every','every','all members, without exception','Every includes all the individual members of the group. None is left out of the marked area.','One outside is enough to make every false in this scene.','every','some','Every {n} is in the marked area.'],
 ['more','more','a greater number','More compares quantities. Count both groups: the left group has four, the right has two.','The individual objects are the same size. Compare the counts, not how large each object looks.','more','fewer','There are more {p} on the left than on the right.'],
 ['fewer','fewer','a smaller number','Fewer compares counts of separate things. Here the left group has two and the right has four.','More reverses the comparison. Fewer is used for countable items in these lessons.','fewer','more','There are fewer {p} on the left than on the right.'],
 ['oneOf','one of','a single member of a group','One of selects a single member from a larger named group. The ring marks just one of six.','The other five remain members of the group even though they are not selected.','oneOf','halfOf','Choose one of the six {p}.'],
 ['halfOf','half of','one of two equal amounts','Half of a group is one of two equal parts by number. Three of six is half because the other half also has three.','One of six is not half. The two parts must be equal in the amount being compared.','halfOf','oneOf','Choose half of the six {p}.'],
 ['before','before','earlier in an order','Before tells which action happens earlier. Read the numbered panels from left to right.','After reverses this relationship. Before alone does not tell us how much earlier.','packFirst','closeFirst','Look at the {n} before closing the box.'],
 ['after','after','later in an order','After tells which action happens later. The box closes first; looking at the object happens afterward.','Before would place looking at the object earlier.','closeFirst','packFirst','Look at the {n} after closing the box.'],
 ['first','first','at the beginning of an order','First identifies the beginning of the sequence. Looking at the object is step one in this picture.','Last identifies the end, not the beginning.','packFirst','closeFirst','First, look at the {n}. Then close the box.'],
 ['last','last','at the end of an order','Last identifies the final step in the stated sequence. Here looking at the object comes at the end.','First identifies the beginning. Follow the panel numbers.','closeFirst','packFirst','First, close the box. Last, look at the {n}.'],
 ['until','until','continuing up to an event','Until marks the event that ends a stated period. Keep the object inside while waiting; the bell marks the point when it may come out.','Until does not mean take it out before the bell. The event sets the boundary.','until','tooSoon','Keep the {n} in the box until the bell rings.'],
 ['over','over','movement above an obstacle','Over can describe movement above an obstacle from one side to another. The route goes higher than the box.','Through would pass inside an opening. This route stays above the obstacle.','over','through','Move the {n} over the box.'],
 ['across','across','from one side to the other','Across describes movement from one side of a space to the other. The arrow crosses the entire mat.','Along the edge would not cross from side to side.','across','along','Move the {n} across the mat.'],
 ['along','along','following a length or edge','Along describes following the length or edge of something. Here the route follows the edge of the mat.','Across cuts from one side to the other instead.','along','across','Move the {n} along the edge of the mat.'],
 ['toward','toward','in the direction of','Toward points in a direction without requiring arrival. The object moves closer but stops short of the box.','To usually identifies a destination. Away from reverses this direction.','toward','away','Move the {n} toward the box.'],
 ['away','away from','increasing the distance','Away from means moving so the gap becomes larger. Compare the start and finish positions.','Toward makes the gap smaller.','away','toward','Move the {n} away from the box.']
];
export const USES=rows.map(([id,word,use,meaning,contrast,scene,wrong,sentence],i)=>({id,word,use,meaning,contrast,scene,wrong,sentence,unit:Math.floor(i/10)}));
const incorrect=[
'next to, but outside','higher up with no contact','resting on top','at a lower position','at a higher position','inside the container','outside the two boxes on the same side','within the boundary','a large distance away','a short distance away',
'starting place','destination','movement from inside to outside','movement from outside to inside','movement away from a surface','movement to a surface','toward a lower position','toward a higher position','following the outside without entering','entering and passing inside',
'one specific thing already identified','one specific thing already identified','any one, with no need to identify which','one farther-away thing','one nearby thing','several farther-away things','several nearby things','introducing a different, new object','a shortened form of it is','far away from the named place',
'choose only one of the two','include both, with no choice allowed','saying the positive statement is true','excluding the other item','including the other item','the person who sent it','the person receiving it, regardless of who packed it','the container is empty','the physical object rather than its representation','the physical location of the book',
'only part of the group','zero members of the group','at least one member of the group','just one member of the pair','just one selected member','some members, with exceptions','a smaller number','a greater number','three members out of six','one member out of six',
'later in the order','earlier in the order','at the end of the order','at the beginning of the order','ending the wait before the stated event','passing through the inside','following only the edge','crossing from one side to the other','increasing the distance','decreasing the distance'
];
USES.forEach((u,i)=>u.incorrect=incorrect[i]);
export const TOTAL=3000;
export function sceneAt(index){if(!Number.isInteger(index)||index<0||index>=TOTAL)throw Error('Unknown academy scene');const round=Math.floor(index/300),slot=index%300,use=USES[Math.floor(slot/5)],object=OBJECTS[round*5+slot%5];const sentence=use.sentence.replaceAll('{n}',object.noun).replaceAll('{p}',object.plural).replaceAll('{article}',object.article);return {id:`a${index}`,index,round,use,object,sentence};}
export function nextIndex(completed){for(let i=0;i<TOTAL;i++)if(!completed[`a${i}`])return i;return null;}
export function stateFor(p){return p.academy||(p.academy={version:1,completed:{},checkpoint:null});}
export function checkpoint(index){return {index,phase:'learn',feedback:null};}
export function canOpen(p,index){const s=stateFor(p);return Number.isInteger(index)&&index>=0&&index<TOTAL&&(Boolean(s.completed[`a${index}`])||nextIndex(s.completed)===index);}
export function complete(p,index,now=Date.now()){const s=stateFor(p);if(!canOpen(p,index)||s.checkpoint?.index!==index||s.checkpoint.phase!=='done')return false;if(!s.completed[`a${index}`]){s.completed[`a${index}`]=now;p.xp+=10;}s.checkpoint=null;return true;}
