import {mergeArcade,validateArcade} from './arcade-model.js';
import {loadSave} from './wordraiders-save.js';
const REGISTRY='wordraiders.players.v1',URL_KEY='wordraiders.sync.url',ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
export const normalizeCode=s=>String(s).toUpperCase().replace(/[\s-]/g,'');
export const validCode=s=>new RegExp(`^[${ALPHABET}]{12}$`).test(s);
export async function pack(raw){if(typeof CompressionStream==='undefined')return raw;const b=new Uint8Array(await new Response(new Blob([raw]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer());let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return 'gz1:'+btoa(s);}
export async function unpack(raw){if(!raw.startsWith('gz1:'))return raw;if(typeof DecompressionStream==='undefined')throw Error('Update this browser to read the synced save.');const reader=new Blob([Uint8Array.from(atob(raw.slice(4)),c=>c.charCodeAt(0))]).stream().pipeThrough(new DecompressionStream('gzip')).getReader();let size=0;const chunks=[];for(;;){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>8000000){await reader.cancel();throw Error('The cloud save is too large.');}chunks.push(r.value);}return new Blob(chunks).text();}
export function validatePlayer(raw){const p=typeof raw==='string'?JSON.parse(raw):structuredClone(raw);if(!p||p.version!==2||typeof p!=='object'||Array.isArray(p))throw Error('This code is not a WordRaiders player code.');if(p.commonWords?.arcade)p.commonWords.arcade=validateArcade(p.commonWords.arcade);if(p.commonWords?.completed&&Object.entries(p.commonWords.completed).some(([k,v])=>!/^a(?:0|[1-9]\d*)$/.test(k)||Number(k.slice(1))>=3000||!Number.isFinite(v)||v<0))throw Error('Invalid Academy progress in the cloud save.');return p;}
export function mergePlayers(local,remote){const newer=Number(local.savedAt||0)>Number(remote.savedAt||0)?local:remote;const out=structuredClone(newer),a=local.commonWords||{},b=remote.commonWords||{},records={...a.records};for(const [k,v] of Object.entries(b.records||{}))if(!records[k]||Number(v.last||0)>=Number(records[k].last||0))records[k]=v;const completed={...a.completed,...b.completed};let checkpoint=newer.commonWords?.checkpoint||null;if(checkpoint&&completed['a'+checkpoint.index])checkpoint=null;out.commonWords={version:1,completed,checkpoint,records,arcade:mergeArcade(a.arcade,b.arcade)};return out;}
export function createWordRaidersSync({getSave,persist,applySave,isBlocked,storage=localStorage,fetchFn=(...args)=>fetch(...args)}){
 let busy=false,dirty=false,timer,preview=null,message='',config;
 const dialog=document.createElement('dialog');dialog.className='academy-sync';dialog.setAttribute('aria-labelledby','wr-sync-title');dialog.innerHTML=`<form method="dialog"><button class="sync-close" aria-label="Close sync">×</button></form><h2 id="wr-sync-title">Sync Small Common Word Academy</h2><p id="wr-sync-player"></p><p>Your Journey, lesson place and Arcade practice sync with your WordRaiders player. You can stay here in the Academy.</p><section id="wr-sync-other"><h3>Enter a code from another device</h3><p>Use the code from the device that has the progress you want to continue.</p><form id="wr-sync-connect"><label for="wr-sync-enter">Code from your other device</label><input id="wr-sync-enter" placeholder="XXXX-XXXX-XXXX" maxlength="16" autocomplete="off" autocapitalize="characters" spellcheck="false" required><button>Find my player</button></form><p>Use your WordRaiders code here. Engineering Quest and the separate Engineering-hosted Academy use different saves.</p></section><section id="wr-sync-linked" hidden><label for="wr-sync-code">This player’s current sync code</label><input id="wr-sync-code" readonly autocomplete="off"><div class="sync-actions"><button id="wr-sync-copy">Copy code</button><button id="wr-sync-now" class="primary">Sync now</button></div><p>On another device, open this Academy, tap Sync, and enter this same code. Keep it private: anyone with the code can access your player.</p></section><section id="wr-sync-unlinked"><label id="wr-sync-name-label" for="wr-sync-name">Your player name<input id="wr-sync-name" maxlength="24" value="Explorer"></label><button id="wr-sync-create" class="primary">Turn on sync</button></section><section id="wr-sync-preview" hidden><p id="wr-sync-preview-text"></p><button id="wr-sync-import">Use this player on this device</button><p>Your other local players are kept.</p></section><p id="wr-sync-message" role="status" aria-live="polite"></p><small id="wr-sync-last"></small>`;document.body.append(dialog);
 const el=id=>dialog.querySelector('#wr-sync-'+id),registry=()=>JSON.parse(storage.getItem(REGISTRY)||'{"active":"","profiles":[]}');
 const active=()=>registry().profiles.find(p=>p.id===getSave().active),key=id=>'wordraiders.save.'+id;
 function report(s){message=s;el('message').textContent=s;}
 function render(){const p=active(),link=p?.sync;el('player').textContent='Player: '+(p?.name||getSave().profiles[0].name);el('linked').hidden=!link;el('unlinked').hidden=!!link;el('name-label').hidden=!!p;el('code').value=link?link.code.match(/.{1,4}/g).join('-'):'';el('last').textContent=link?.at?'Last synced: '+new Date(link.at).toLocaleString():'';el('message').textContent=message;dialog.querySelectorAll('button:not(.sync-close)').forEach(b=>b.disabled=busy);}
 function read(id){if(isBlocked())throw Error('Saving is unavailable on this device.');return validatePlayer(storage.getItem(key(id))||'{}');}
 function putLink(id,link){const r=registry(),p=r.profiles.find(p=>p.id===id);if(!p)throw Error('Player no longer exists on this device.');p.sync=link;storage.setItem(REGISTRY,JSON.stringify(r));}
 async function server(){if(config)return config;const local=storage.getItem(URL_KEY);if(local&&/^https?:\/\//.test(local))return config=local.replace(/\/$/,'');const r=await fetchFn('../sync.json',{cache:'no-store'});if(!r.ok)throw Error('The sync service configuration could not be loaded.');const c=await r.json();if(typeof c.url!=='string'||!/^https?:\/\//.test(c.url))throw Error('The sync service is not configured.');return config=c.url.replace(/\/$/,'');}
 async function request(code,payload,rev=0){if(!validCode(code))throw Error('Enter the complete 12-character WordRaiders code.');const url=await server(),options={cache:'no-store',signal:AbortSignal.timeout(20000)};if(payload){const body=JSON.stringify({data:await pack(JSON.stringify(payload)),baseRev:rev,savedAt:payload.savedAt||Date.now()});if(body.length>400*1024)throw Error('The save exceeds the cloud size limit. Export a backup in WordRaiders Settings.');Object.assign(options,{method:'POST',headers:{'content-type':'text/plain'},body});}const res=await fetchFn(url+'/v1/save/'+code,options);if(res.status===404)return null;const x=await res.json();if(res.status===409&&x.conflict)return {conflict:true,rev:x.rev,data:validatePlayer(await unpack(x.data))};if(!res.ok)throw Error(x.error||'The sync service could not be reached.');if(!Number.isInteger(x.rev))throw Error('Invalid sync response.');return {rev:x.rev,...(typeof x.data==='string'?{data:validatePlayer(await unpack(x.data))}:{})};}
 function apply(id,cloud){const old=read(id),merged=mergePlayers(old,cloud);if(JSON.stringify(old)!==JSON.stringify(merged)){storage.setItem(key(id)+'.before-academy-sync',JSON.stringify(old));storage.setItem(key(id),JSON.stringify(merged));if(getSave().active===id&&(JSON.stringify(old.commonWords)!==JSON.stringify(merged.commonWords)||old.xp!==merged.xp))applySave(loadSave(storage).save);}return merged;}
 async function syncOne(){if(isBlocked())throw Error('Saving is unavailable on this device.');const p=active(),id=p?.id,link=p?.sync;if(!link)return;let remote=await request(link.code);if(!remote)throw Error('No player was found for this code.');for(let tries=0;tries<4;tries++){const combined=mergePlayers(read(id),remote.data);if(JSON.stringify(combined)===JSON.stringify(remote.data)){apply(id,combined);putLink(id,{code:link.code,rev:remote.rev,at:combined.savedAt||Date.now()});return;}combined.savedAt=Math.max(Number(combined.savedAt)||0,Date.now());const result=await request(link.code,combined,remote.rev);if(result.conflict){remote=result;continue;}apply(id,combined);putLink(id,{code:link.code,rev:result.rev,at:combined.savedAt});return;}throw Error('Another device is syncing. Try again.');}
 function schedule(){clearTimeout(timer);timer=setTimeout(sync,15000);}
 async function run(action){if(busy)return;busy=true;render();try{await action();}catch(e){report('Not synced. '+(e.name==='TimeoutError'?'The connection timed out.':e.message)+' Your existing progress stays on this device.');}finally{busy=false;render();if(dirty)schedule();}}
 async function sync(){if(!active()?.sync)return;if(busy){dirty=true;return;}await run(async()=>{dirty=false;report('Syncing Academy progress…');await syncOne();report('Synced. Journey and Arcade progress are saved across your linked devices.');});}
 el('create').onclick=()=>run(async()=>{if(!persist())throw Error('Your progress could not be saved locally.');let p=active();if(!p){const r=registry();if(r.profiles.length>=8)throw Error('This device already has eight players. Choose one in WordRaiders first.');const id='p'+crypto.randomUUID().replaceAll('-','').slice(0,12),name=el('name').value.trim().slice(0,24)||'Explorer';p={id,name,color:'#bfff73',pin:'',createdAt:Date.now(),lastPlayed:Date.now()};const guest=JSON.parse(storage.getItem(getSave().key)||'{}');storage.setItem(key(id),JSON.stringify({...guest,version:2,name,color:p.color,savedAt:Date.now()}));r.profiles.push(p);r.active=id;storage.setItem(REGISTRY,JSON.stringify(r));applySave(loadSave(storage).save);}const code=Array.from(crypto.getRandomValues(new Uint8Array(12)),n=>ALPHABET[n%ALPHABET.length]).join('');const data=read(p.id);data.savedAt=Date.now();report('Turning on sync…');const r=await request(code,data,0);if(r.conflict)throw Error('Please try creating the code again.');putLink(p.id,{code,rev:r.rev,at:data.savedAt});report('Sync is on. Enter this code on your other device.');});
 el('connect').onsubmit=e=>{e.preventDefault();run(async()=>{preview=null;el('preview').hidden=true;const code=normalizeCode(el('enter').value),r=await request(code);if(!r)throw Error('No player was found. Check the code on your first device.');preview={code,...r};el('preview-text').textContent=String(r.data.name||'Explorer')+' — '+Object.keys(r.data.commonWords?.completed||{}).length+' of 3,000 scenes completed';el('preview').hidden=false;report('Check the player above, then connect.');});};
 el('import').onclick=()=>run(async()=>{if(!preview)return;if(!persist())throw Error('Your local progress could not be saved.');const {code,data,rev}=preview,r=registry();let p=r.profiles.find(p=>p.sync?.code===code);if(p){apply(p.id,data);}else{if(r.profiles.length>=8)throw Error('This device already has eight players.');const id='p'+crypto.randomUUID().replaceAll('-','').slice(0,12);p={id,name:String(data.name||'Explorer').slice(0,24),color:data.color||'#bfff73',pin:'',createdAt:Date.now(),lastPlayed:Date.now(),sync:{code,rev,at:0}};r.profiles.push(p);storage.setItem(key(id),JSON.stringify(data));}r.active=p.id;storage.setItem(REGISTRY,JSON.stringify(r));putLink(p.id,{code,rev,at:0});applySave(loadSave(storage).save);await syncOne();preview=null;el('preview').hidden=true;report('Connected and synced. Continue Small Common Word Academy here.');});
 el('copy').onclick=async()=>{try{await navigator.clipboard.writeText(el('code').value);report('Code copied.');}catch{el('code').select();report('Select and copy the code above.');}};el('now').onclick=sync;
 document.addEventListener('click',e=>{if(e.target.closest('[data-action="sync"]')){preview=null;el('preview').hidden=true;render();dialog.showModal();}});
 window.addEventListener('online',sync);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync();});setInterval(()=>{if(!document.hidden&&!busy)sync();},60000);
 return {changed(){dirty=true;if(active()?.sync)schedule();},start(){sync();}};
}
