// Eight entry points per act. Each answer can branch into pressure or visible evidence.
const packs=[
 ['Which image made you want to tell this story?','Who is affected by that image?','What changes on this particular day?','What question would make you keep watching?','Where could you film the central event?','What is the smallest version of your idea?','What should the audience wonder at the start?','Which ending image keeps returning to you?'],
 ['What does the person want in the next ten minutes?','Who can refuse what they need?','What will be lost if they fail?','What are they afraid to admit?','What contradictory habit makes the task harder?','Why must they act today?','What does the other person want?','What would they refuse to sacrifice?'],
 ['What did they try that already failed?','What changes because of that failure?','What harder attempt follows?','What new information changes the plan?','Which choice cannot be undone?','What is the most difficult final choice?','What causes the ending?','How does the opening gain new meaning?'],
 ['If sound is off, what do we see?','Which object carries the secret?','What gesture contradicts the words?','What sound changes the next action?','Where does the audience look first?','What information can remain offscreen?','What action reveals a feeling?','Which repeated image changes meaning?'],
 ['What do they want in this room?','What is the tactic under this line?','What happens if they say nothing?','Where does the scene turn?','How late could the scene begin?','What line can become behavior?','How does this character choose words?','What must the next scene inherit?'],
 ['Where did your reader become confused?','Which moment surprised the reader?','What does the timed read reveal?','Which revision changes the story most?','Which location or prop can be simplified?','What does the ending now communicate?','What evidence supports your intended theme?','How would you pitch the central pursuit?']
];
const followups=[['What makes this moment difficult?','What visible detail would let the audience understand it?'],['Who or what pushes back?','What behavior shows the cost without explaining it?'],['Why must the next attempt be different?','What changed on screen because of this choice?'],['What happens if the audience misses this clue?','What could the camera or microphone actually capture?'],['How does the other person resist this tactic?','What does the actor do during or instead of this line?'],['Which change will you test in the next read?','Which exact scene or line is your evidence?']];
export const coachPacks=packs.map((questions,act)=>({act,nodes:questions.flatMap((question,i)=>{const id=`act${act+1}-${i+1}`;return [{id,question,next:[id+'-pressure',id+'-visible']},{id:id+'-pressure',question:followups[act][0],next:[id+'-visible']},{id:id+'-visible',question:followups[act][1],next:[]}];})}));
