// Original instruction adapted from the user's handbook; supplemental format references in SOURCES.md.
export const acts = [
 {name:'Find your story',sub:'Turn a spark into something that moves.',icon:'✦',color:'#dce99a'},
 {name:'Build the engine',sub:'A person, a want, and a price.',icon:'◈',color:'#eab99a'},
 {name:'Make it move',sub:'Design cause, pressure, and a choice.',icon:'↗',color:'#b7c9ed'},
 {name:'Think in pictures',sub:'Write what a camera and microphone can capture.',icon:'▣',color:'#b8d8bf'},
 {name:'Write the film',sub:'From scene cards to a complete screenplay.',icon:'▤',color:'#ddbee5'},
 {name:'Earn the ending',sub:'Read, diagnose, revise, and finish.',icon:'★',color:'#edcf8b'}
];
const q=(prompt,correct,wrong1,wrong2,why)=>({prompt,options:[correct,wrong1,wrong2],answer:0,why});
const l=(title,term,definition,teach,before,after,why,field,prompt,checks,questions,ref)=>({title,term,definition,teach,before,after,why,field,prompt,checks,questions,ref});
export const lessons=[
l('A spark is a beginning','Story','A chain of meaningful events involving a person, resistance, and a change.',
['You do not need a polished idea. Start with a person, image, question, or awkward moment that interests you. A situation describes what exists. A dramatic story explores what someone does when staying the same becomes difficult.','We will build a short, character-centered film. This is one useful approach, not a law that excludes experimental films, portraits, or comedies. Your first assignment is simply to collect possibilities.'],
'A caretaker sits alone in a closed theater.','A caretaker must remove the last seat before demolition, but his late wife’s name is on it.','The second version gives the person a task and a reason it hurts. It creates a question we can follow.',
'sparks','Write three possible film ideas, one per line. Include a person and something they might have to do. Choose one by putting a star beside it.', ['I collected three specific possibilities.','I chose an idea I care about.'],[
q('Which idea already contains dramatic pressure?','A cook must serve dinner after discovering her rival is the guest.','A restaurant is beautiful.','A cook likes music.','The cook has a task made difficult by a specific circumstance.'),
q('What should you do with an interesting image first?','Explore who acts, what resists, and what could change.','Assume the image is a finished plot.','Add ten unrelated events.','A spark is raw material; investigate its possible dramatic engine.')],'I; X.1'),
l('Give your idea a shape','Premise','The central situation or possibility your story explores.',
['A premise is the seed of the film. A logline is a compact description of its dramatic engine. Neither needs to explain every scene. Choose one of your sparks and make the task concrete.','Use this temporary scaffold: When something disrupts a person’s day, they try to do a specific thing, despite a specific obstacle, or face a particular loss. Change the sentence if the scaffold fights your idea.'],
'A man learns to care.','Before a shelter closes, a man who avoids commitment tries to return a runaway dog—but the dog keeps leading him back to its abandoned owner’s door.','We can imagine actions, a time limit, and a personal tension without a full biography.',
'logline','Write one or two sentences naming your central person, their task, the main resistance, and the consequence of failure.', ['The task could be filmed.','The resistance and consequence are specific.'],[
q('Which phrase names a visible task?','Deliver the apology letter before the train leaves.','Find inner peace.','Understand existence.','Delivering a letter is an action with a visible success or failure.'),
q('A logline is most useful for…','Checking the central dramatic engine.','Listing every camera angle.','Replacing a complete script.','It compresses the person, pursuit, and pressure so you can check whether they connect.')],'I; Appendix'),
l('Choose a short-sized promise','Scope','The amount of story, time, and production complexity you take on.',
['A first short becomes manageable when it concentrates on one important event. Try a 3–10 minute target, one main person, a small cast, and places you can access. These are training constraints, not requirements of the art form.','A five-minute story can reveal a relationship through a single choice. It does not need to explain a whole childhood. Keep other ideas in your idea bank for later.'],
'Three generations fight a war across seven countries.','Two siblings sort one box before their childhood home is handed over.','A small physical task can contain a large emotional history.',
'scope','Set a target length. List the people, places, props, and effects your story needs. Name one complication you can simplify.', ['I chose a manageable duration.','I can explain how to stage the essential action.'],[
q('Which is the most manageable first-film scope?','Two people deciding who keeps one object.','A city-wide evacuation with hundreds of extras.','A biography covering sixty years.','A contained decision reduces production demands while allowing emotional depth.'),
q('Does a short have to be exactly ten minutes?','No; length should serve the story and intended use.','Yes; all shorts are ten minutes.','No; it must be forty minutes.','Training targets help you choose; they are not universal definitions.')],'V'),
l('Promise a feeling','Tone','The emotional manner in which a film invites us to experience its events.',
['Tone might be playful, uneasy, tender, or bleak. Establish it through behavior, pacing, image, and sound. A tonal shift can work when the story prepares it.','Pick a feeling more precise than good or sad: relief mixed with regret, the embarrassment of needing help, or the pleasure of a small rebellion. The goal guides choices; it cannot guarantee everyone reacts identically.'],
'A funny opening becomes violent without preparation.','A comic argument keeps revealing a bruise in the relationship, preparing a painful choice.','A shift can feel earned when details make the deeper tension visible.',
'feeling','Describe the feeling you want to leave behind. Write an opening action or sound that sets that emotional contract.', ['My desired feeling is specific.','My opening suggests how the audience should watch.'],[
q('Which opening establishes unease through behavior?','She checks three locks, then hears a key turn.','A title says this is tense.','The writer calls the film impressive.','Behavior and sound create the experience rather than merely labeling it.'),
q('Can a comedy become painful?','Yes, if the transition is meaningfully prepared.','Never.','Only by changing all the characters.','Tone can shift; the shift should grow from the story.')],'III; V'),
l('Meet the person under pressure','Protagonist','The central person whose pursuit or experience organizes this story.',
['A character is more than a list of traits. Show a repeatable way they handle a problem. Do they bargain, avoid, organize, joke, control, or ask for help?','Give them a specific situation and an understandable reason for acting. The audience can follow someone they do not approve of. Avoid making identity or diagnosis a shortcut for personality.'],
'Mara is proud and stubborn.','Mara repairs a cracked sign herself while hiding the invoice from her daughter.','The action reveals pride, a relationship, and a practical problem at once.',
'character','Introduce your main person through one behavior. Explain privately why that behavior makes sense to them.', ['I described behavior, not just traits.','I know why this person acts this way.'],[
q('Which introduction gives an actor something to play?','He wipes his muddy shoes before entering a ruined house.','He represents hope.','He has a complex soul.','The specific action can reveal values through performance.'),
q('Must the protagonist be morally admirable?','No; we need to understand their pursuit and pressures.','Yes, always.','Only villains can be protagonists.','Comprehensible motivation and likability are different things.')],'II; III'),
l('Separate want from need','Want and need','Want is the pursued goal; need is an underlying change or recognition the story explores.',
['Want supplies a trackable pursuit: get a key, finish a meal, stop a departure. Need asks what that pursuit reveals or challenges: accepting help, speaking honestly, or setting a boundary.','Not every character must learn a lesson. They may refuse change or stay principled while the world changes. Use want and need to explore tension rather than force a moral conversion.'],
'She wants to heal.','She wants to repair her father’s radio before selling it; she may need to accept that keeping a memory is not the same as keeping an object.','A practical action carries an internal question.',
'wantNeed','Write WANT: the visible goal. Then NEED OR TENSION: what the pursuit challenges in the person. Allow refusal or uncertainty if it serves your film.', ['My want has an observable result.','My inner tension differs from the physical task.'],[
q('Which is an external want?','Get the shop key back today.','Accept uncertainty.','Become less ashamed.','A key can be obtained or lost; the others describe possible inner changes.'),
q('A protagonist fails to win but finally tells the truth. Can the story feel complete?','Yes; the external result and inner change can differ.','No; success is mandatory.','Only if a narrator explains the moral.','A loss of the want can accompany a meaningful change.')],'II'),
l('Build real resistance','Obstacle','Something that makes the desired action difficult or costly.',
['An obstacle can be another person, a system, limited time, the environment, or the protagonist’s own method. It need not be a villain.','Give another person a legitimate competing want. Then make the protagonist choose a tactic—an action used to pursue the goal. A tactic that fails should lead to an adjustment, not endless repetition.'],
'The neighbor is mean because the story needs trouble.','The neighbor will not lend the van because it is the only way to get her father to an appointment.','Both people have reasons. The conflict grows from incompatible needs.',
'obstacle','Name the main resistance. If it is a person, write what they want. List your protagonist’s first tactic and why it cannot fully work.', ['The obstacle directly blocks the goal.','Its resistance has a believable reason.'],[
q('Which obstacle directly opposes returning a package?','The recipient refuses to open the door.','The sky is blue.','The courier remembers a favorite song.','The closed door changes what the courier must do.'),
q('What is a tactic?','A specific method used to get something.','The same thing as a film’s genre.','Any location change.','Charm, bargaining, avoidance, or confession can be tactics when used to pursue a goal.')],'II; VII'),
l('Put something at risk','Stakes','What may be lost or gained because of the outcome.',
['Stakes answer why this attempt matters. A deadline answers why it matters now. Small stakes can be powerful when the relationship or meaning is clear.','Avoid attaching a random catastrophe just to make events bigger. Connect the cost to the person’s values. Completing the task can cost something too: getting the apology may expose your own part in the fight.'],
'He might be disappointed.','If he misses the last bus, his daughter will perform to another empty chair.','The consequence is intimate, visible, and connected to a relationship.',
'stakes','Write the consequence of failure, the cost of success, and the reason your person must act now.', ['The consequence matters to this person.','The urgency grows from the situation.'],[
q('Which is a meaningful clock?','The buyer arrives in ten minutes to take the piano.','The film is called Hurry.','A timer appears with no consequence.','The arrival changes the character’s remaining options.'),
q('Must stakes involve death?','No; trust, dignity, belonging, or a final chance can matter.','Yes.','Only money counts.','Specific personal meaning can make a small event emotionally large.')],'II; IV'),
l('Connect cause to consequence','Causality','The relationship in which one event brings about or changes the conditions for another.',
['A beat is a small meaningful shift. Link beats by because, therefore, or but to test their relationship. Those words do not magically create logic; the events must actually connect.','An unrelated event can deliberately interrupt a story, but repeated coincidence can remove the protagonist’s influence. Look for choices that make the next problem unavoidable.'],
'He loses a key. Then he buys soup. Then a stranger arrives.','He hides the key, so his sister cannot leave; but she finds the spare, forcing him to say why he wants her to stay.','The second sequence puts the next event under pressure from the previous choice.',
'causality','Write four connected beats of your film. Between each, explain the cause, result, or meaningful complication.', ['The links express real consequences.','At least one problem follows from a choice.'],[
q('Which continuation follows causally from a lie about a broken oven?','The guest asks to heat the dish they brought.','An unrelated parade passes.','A title announces tomorrow.','The guest’s request puts pressure on the specific lie.'),
q('Adding the word therefore to unrelated events…','Does not create a believable causal link.','Always repairs the plot.','Makes a scene longer but better.','Logic comes from the events, not the connector word.')],'I; IV'),
l('Build a story spine','Story spine','A brief outline of the essential before, disruption, attempts, choice, and after.',
['An inciting incident is the disruption that starts the central pressure. A climax is the decisive high point of that pressure. A resolution shows the resulting condition. Learn the functions before worrying about labels.','A short can carry these functions in one scene. Do not pad your idea to meet fixed page numbers. The outline is a tool for finding missing relationships, not a required formula.'],
'Beginning: introduce everyone. Middle: more things. End: a speech.','Before: she keeps the shop closed. Disruption: a child brings a broken toy. Attempts: she refuses, then repairs it secretly. Choice: she opens the door. After: another person is allowed inside.','The outline names changes instead of vague sections.',
'spine','Write five short lines: Before / Disruption / Attempts and costs / Decisive choice / After.', ['The disruption changes the available options.','The ending follows from the attempt and choice.'],[
q('The inciting incident is…','The event that disrupts the starting condition.','Always an explosion.','The final credits.','Its job is to disturb the situation; its size can be small.'),
q('A short with one location can have a complete structure because…','Structure concerns changing pressure, not number of locations.','Every room is automatically an act.','Shorts do not need any progression.','Before, pressure, and after can happen in the same room.')],'IV; X'),
l('Make each attempt cost more','Escalation','A progression that makes the problem more consequential or the options harder.',
['Escalation does not mean louder voices each minute. An easy tactic may stop working; a secret may become visible; a person may have to choose between two things they value.','Build at least two meaningfully different attempts. After the first, ask what is no longer possible. The next choice should operate in that changed situation.'],
'He asks louder. Then louder again.','He jokes to avoid returning the key. When that fails, he bargains with a treasured object. When she refuses, he must speak plainly or lose her.','The tactics expose more vulnerability instead of merely increasing volume.',
'attempts','Write Attempt 1 → result and cost. Then Attempt 2 → new result and higher or different cost.', ['The attempts use different tactics.','The first result changes the next choice.'],[
q('Which raises pressure most meaningfully?','Her lie now requires blaming someone she cares about.','The same argument is repeated at higher volume.','An extra lamp turns on.','The new cost tests what matters to her.'),
q('An attempt succeeds but creates a new problem. Is that escalation?','Yes, if the new problem changes the costs or choices.','No, every attempt must fail.','Only in action movies.','Success can be complicated; dramatic progression is not a string of identical failures.')],'II; IV'),
l('Make a choice that leaves a mark','Climax','The decisive moment in the story’s central conflict.',
['A climactic choice can be quiet: return a key, confess, stay, refuse, or let go. Its meaning depends on the pressure you established. Show the consequence rather than declaring that everything changed.','An ending may leave future events uncertain while still completing the immediate event. A reversal should have earlier support. A surprise ending is optional.'],
'A stranger solves her problem and tells her what it means.','She returns the key even though it means she can no longer enter unnoticed. The lock clicks shut.','The protagonist acts and pays a concrete price. The future remains open, but this decision lands.',
'ending','Describe the decisive choice and its cost. Then write the final visible action. What is now different for the person, relationship, world, or audience?', ['The choice grows from prior pressure.','The last moment demonstrates a meaningful difference.'],[
q('Which ending is earned by a story about refusing help?','She hands over the tool she has guarded all day.','A previously unmentioned millionaire fixes everything.','A title explains she is now better.','The action answers the established tension in a visible way.'),
q('An open ending should still…','Give the central event a meaningful turn or consequence.','Stop at an arbitrary moment.','Explain every future outcome.','Uncertainty about the future can coexist with a clear dramatic change.')],'II; IV; V'),
l('Translate thought into behavior','Visual action','What can be seen happening in the world of the film.',
['A prose story can directly describe a thought. A screenplay mainly communicates through action and sound. Translate an abstract sentence into something an actor can do and an audience can interpret.','The silent-scene exercise sharpens visual storytelling. It does not mean dialogue-heavy cinema is invalid. Choose details particular to this person and context.'],
'She feels guilty about what she did.','She wipes her fingerprints from the gift, then puts it back in the child’s room.','The audience infers an inner conflict from concrete behavior.',
'silentScene','Write a brief scene with no dialogue: a task, resistance, a changed action, and a consequence. Use your own story if possible.', ['Everything essential can be seen or heard.','A task or relationship changes during the scene.'],[
q('Which is directly filmable?','He folds the rejection letter into a tiny square.','He understands the nature of time.','She knows her destiny.','Folding a letter is visible; context can give the gesture meaning.'),
q('The mute test is…','A useful exercise for finding physical storytelling.','Proof that all dialogue is bad.','A required rule for every film.','It develops a skill without defining the only valid kind of cinema.')],'VI; XII.D'),
l('Give objects and sound a job','Motif','A recurring detail whose repetition or changed use adds meaning.',
['An object can help reveal change: the same chair is first guarded, then offered. Space can express power: who holds the doorway, who sits, who must stand?','Sound can reveal off-screen action or change what we think a moment means. Write a meaningful sound where the reader needs it. Do not require expensive spectacle when a sound and reaction could tell the essential story.'],
'We see a huge crowd leave the station.','A departure whistle cuts through the kitchen. She stops stirring. The untouched second bowl remains.','A sound, a gesture, and an object can create consequence economically.',
'imageSound','Write your first and last images. Choose one repeated object and one meaningful sound or silence. Explain what changes in their meaning.', ['The repeated detail does story work.','The sound changes what the audience knows or feels.'],[
q('A cup is a useful motif when…','How it is handled changes with the relationship.','It appears randomly in every shot.','It is expensive.','The repeated detail earns meaning through context and variation.'),
q('An off-screen crash can help a short by…','Making an unseen event legible through sound and reaction.','Automatically proving who caused it.','Replacing all character choices.','Sound can imply action; the script must still control what is clear and what is unknown.')],'VI'),
l('Control what we know','Dramatic irony','A difference in knowledge where the audience knows something a character does not.',
['Curiosity asks what is going on. Suspense asks what will happen to a known concern. Dramatic irony lets us watch someone act without knowledge we possess. They can overlap.','Choose the audience’s information deliberately. A mystery needs enough orientation to make its missing information interesting. Withholding the basic goal can create confusion rather than suspense.'],
'A person looks worried for unexplained reasons.','We see the rejection letter before he tells his mother the interview went well.','We understand both the spoken conversation and the danger underneath it.',
'information','For your opening, middle, and ending, list what the audience knows, what the protagonist knows, and what you deliberately withhold.', ['The audience can identify the central concern.','My withheld information has a purposeful payoff or effect.'],[
q('We see a key hidden in a coat; the owner searches the room. This is…','Dramatic irony.','A scene heading.','A production schedule.','The audience has relevant information the character lacks.'),
q('Which creates suspense rather than basic confusion?','We know the goal and fear a visible obstacle will stop it.','We cannot identify anyone or their goal.','Every important fact is unexplained.','Suspense gives us something to hope for and fear.')],'III; IV'),
l('Let theme become a choice','Theme','An underlying question or idea explored through the story’s events.',
['Turn a slogan into a question: instead of family is important, ask what we owe someone who repeatedly disappoints us. Give different people plausible answers.','The ending can test those answers through action. A film does not need a moral lecture or a correct answer for everyone. Your specific people should remain more interesting than your argument.'],
'He says: You must always forgive your family.','He leaves food at his brother’s door but keeps his own house key.','The action holds care and a boundary at once. It asks a richer question than a slogan.',
'theme','Write a difficult question your film explores. Give two plausible answers, then describe the action that tests them in the ending.', ['More than one answer is plausible.','The ending explores the question through an action.'],[
q('Which is a useful theme question?','Can you care for someone without rescuing them?','What color is the wall?','Why is my film definitely correct?','It allows competing values to be tested in specific actions.'),
q('How can a film express a boundary without a speech?','Show someone offering help while keeping their key.','Add the word boundary to every line.','Explain the theme in every scene.','A concrete choice can carry competing meanings.')],'IX'),
l('Build scenes that turn','Scene turn','A meaningful change in information, power, feeling, or circumstances within a scene.',
['A scene is a unit of continuous action, often in one time and place. For this course, design each major scene around a purpose, tactic, resistance, turn, and resulting situation.','Label a change: trust becomes suspicion, refusal becomes negotiation, or safety becomes exposure. Some passages orient or create atmosphere; judge their contribution rather than mechanically deleting every quiet moment.'],
'They discuss the key for two pages and leave exactly as they arrived.','She asks for the key as a favor. He admits he copied it. Now the scene is about trust, not access.','New information changes the relationship and what the next action means.',
'scenePlan','Outline 3–8 scenes, or fewer if your short needs fewer. For each write: purpose / tactic / resistance / turn / new situation.', ['Each major scene contributes a distinct change.','I can explain why this order matters.'],[
q('Which is a scene turn?','A request for help becomes a demand for an apology.','A character walks from left to right without consequence.','The room is described again.','The purpose or power changes, giving the scene a new direction.'),
q('Start late and leave early means…','Keep the setup needed for clarity and exit after the useful turn.','Remove all context.','Always begin at night.','It is about economical dramatic entry and exit, not confusion.')],'VII; X.6'),
l('Make dialogue do something','Subtext','Meaning or intention suggested beneath the literal words.',
['Dialogue can invite, dodge, test, bargain, wound, or reassure. Ask what each speaker wants the words to accomplish. People may say something true while avoiding the most difficult truth.','Let characters use different rhythms and vocabulary. Read the scene aloud to hear stiffness. Direct speech is allowed when the moment earns it; subtext is a tool, not a ban on honesty.'],
'I am lonely and afraid you will leave.','While packing two lunches, he asks: You still taking the early train?','The action and situation can turn a practical question into a plea.',
'dialogue','Write a short exchange between two people with incompatible wants. Beneath it, name each person’s tactic and what they avoid saying.', ['The lines pursue something.','The action and context support the implied meaning.'],[
q('In a goodbye scene, “I made too much coffee” might function as…','An indirect invitation to stay.','A guaranteed literal recipe instruction.','A scene heading.','Context and behavior can make ordinary words carry a second intention.'),
q('When characters sound interchangeable, try…','Changing rhythms, word choices, and what each avoids.','Adding more identical exposition.','Removing their goals.','Voice grows from differing people and tactics.')],'VIII'),
l('Write a treatment, then learn the page','Treatment','A prose account of the film’s visible and audible events in order.',
['Write a short treatment in present tense before drafting. Keep the causal spine, key behavior, and ending. A treatment tells what happens; it is not a promotional teaser that hides the ending.','A screenplay uses scene headings, action, character cues, and dialogue. A heading gives interior or exterior, place, and time: INT. KITCHEN - NIGHT. Action describes what we see or hear; a character cue identifies the speaker.'],
'She was thinking about the important decision she would make.','INT. KITCHEN - NIGHT\n\nMARA closes the suitcase. A key rattles inside.\n\nMARA\nKeep the spare.','The page makes place, action, and speech easy to distinguish. INT. means interior; EXT. means exterior.',
'treatment','Write a 300–600 word treatment, or a proportionally shorter treatment for a very brief film. Include the ending. Then identify where your first scene heading belongs.', ['Events are written in present tense.','The treatment includes the decisive choice and ending.'],[
q('What does INT. mean in a scene heading?','Interior: the scene takes place inside.','Interruption.','Internal thoughts.','INT. and EXT. help identify the physical setting.'),
q('A treatment should generally…','Tell the essential events, including the ending.','Conceal all events like a teaser.','Contain only camera lens choices.','It is a development tool for examining the complete story.')],'X.7; Academy format guide'),
l('Finish a complete first draft','Screenplay','A written plan for a film using scene headings, action, and dialogue.',
['Write from the first moment through the final image. Use the studio’s scene cards to build your script. Each card has a heading, action, and optional dialogue blocks. Export to Fountain, a plain-text screenplay format, when ready.','Typical U.S. scripts use a monospaced 12-point Courier-style font and readable margins. A formatted page is only a rough planning proxy for a minute: a line of action might take seconds or several minutes. Time a read-through and stage key actions rather than trusting word count.'],
'A polished opening with no ending.','A rough complete draft with an ending you can evaluate.','Completion reveals the whole shape. Revision can improve a whole draft more intelligently than an isolated opening.',
'draftNotes','Use My film → Screenplay to write every scene through the ending. Here, record the largest problem you noticed while finishing. Do not solve everything at once.', ['I reached the final image in my screenplay.','I kept essential actions and speaker names legible.'],[
q('Which is a reliable runtime check?','Time a read-through and allow for the physical action.','Divide all words by a fixed number and call it exact.','Assume every page always lasts sixty seconds.','Formatting and performance alter timing; actual reading and staging are better checks.'),
q('A character cue primarily tells the reader…','Who speaks the following dialogue.','What lens to use.','The film’s budget.','The cue separates speech by character; action occupies its own paragraphs.')],'X.8; Appendix; Academy; Fountain'),
l('Diagnose before polishing','Revision','Reconsidering a draft to improve its structure, clarity, and effect.',
['If the story drags, check the goal and consequences. If it confuses, check orientation and information. If it feels preachy, put the argument into conflicting actions. If a twist carries everything, ask whether the earlier experience is worth watching.','Revise in passes: story logic first, scene turns second, action and dialogue third, format last. The handbook’s cut-thirty-percent exercise is a challenge to find redundancy, not a quota every film must meet.'],
'Change every adjective because the draft feels wrong.','Identify that scene three repeats scene two; combine the scenes and preserve the one new fact.','Diagnosis connects an edit to a concrete problem.',
'diagnosis','Name the biggest story problem and point to the scene that shows it. Propose a change and explain what you expect it to improve.', ['My diagnosis names evidence in the draft.','My proposed change targets that problem.'],[
q('Two scenes repeat the same emotional turn. First consider…','Combining them while retaining essential new information.','Adding a third identical scene.','Changing only the font.','A structural repetition needs a structural examination.'),
q('Must every rewrite remove exactly thirty percent?','No; remove what is redundant without damaging clarity or rhythm.','Yes, regardless of the result.','Only dialogue counts as removable.','Cutting is a diagnostic exercise, not a mathematical law.')],'XI; X.9; XII.E'),
l('Hear it outside your head','Table read','A read-through in which the screenplay is spoken aloud.',
['Invite a willing reader, or record yourself reading it first. Ask what they wanted to happen, where they felt lost, and what changed by the end. Let them answer before explaining your intent.','Record observations separately from proposed solutions. You choose the rewrite. Time the dialogue and allow for silent action; a spoken read alone can underestimate or misrepresent the finished duration.'],
'Did you like it? Yes.','What did Mara want? When did your understanding change? Which moment was unclear?','Specific questions produce evidence you can use.',
'readNotes','Record a timed read or rehearsal. Include who read it, approximate time including action, one confusing moment, and one response that surprised you.', ['I tested the script aloud and considered silent action.','I recorded a concrete observation before defending the draft.'],[
q('The most useful feedback question is…','At what moment were you unsure what she wanted?','You liked it, right?','Would you agree everything works?','Specific neutral questions invite observations rather than approval.'),
q('A reader misunderstands the ending. What next?','Locate the missing or misleading evidence before deciding how to revise.','Explain it to every future viewer.','Assume all ambiguity is a mistake.','Investigate the mismatch; then decide whether it is intended ambiguity or a clarity problem.')],'X.10; XII'),
l('Rewrite and make it filmable','Production constraint','A practical limit affecting how a story can be filmed.',
['Check cast, locations, permission needs, sound, props, effects, and difficult action. Preserve the dramatic function while simplifying how it appears. You can imply a larger world without showing everything.','Save a draft snapshot before rewriting. Keep a revision note: what changed, why, and what evidence would show it works better. The goal is a stronger film, not a higher word count.'],
'Show a dangerous highway collision with no plan or resources.','Keep the character inside a stationary room; a call and a changed task convey the aftermath.','The dramatic consequence may survive with a much more manageable scene.',
'revision','Revise your screenplay. Record three meaningful changes, their reasons, and a practical filming plan for cast, locations, sound, and challenging action.', ['The revised draft differs meaningfully from the first.','I checked the practical requirements of the film.'],[
q('When an expensive scene blocks the project, ask…','What dramatic function can a simpler scene preserve?','How can I remove the protagonist’s goal?','Which unrelated spectacle can I add?','Preserving function while changing staging keeps the story coherent.'),
q('A useful revision note records…','The change, the reason, and the effect to check.','Only the new page count.','That the writer tried harder.','Revision becomes deliberate when edits are connected to an intended improvement.')],'V; VI; X'),
l('Your first finished short','Capstone','A final project that demonstrates the skills you have practiced.',
['A quiz can check concepts; it cannot certify that a screenplay moves an audience. Complete the course by presenting a revised script, a clear pitch, and evidence from a reader or rehearsal.','Use the screening checklist in My film. Support each judgment with a specific scene or line. Completing these steps means you have practiced an end-to-end writing process; mastery develops across more films, feedback, and production.'],
'I earned points, so the screenplay must be excellent.','I can describe the goal, show the change, explain my revision choices, and test the film with a reader.','Evidence of writing and revision is more useful than an automatic artistic grade.',
'pitch','Write a 30-second spoken pitch: the person, pursuit, resistance, emotional question, and intended length. Then complete the Screening room review for this project.', ['I can explain the film in plain language.','I completed an evidence-based review of the revised script.'],[
q('What best demonstrates readiness to write another short?','A completed, tested, revised script and an understood process.','Memorizing vocabulary alone.','A streak with no written work.','The final outcome is transferred practice, not recognition alone.'),
q('A game completion badge means…','You completed this learning process, not that artistic quality is guaranteed.','Your film is guaranteed festival selection.','You never need outside feedback.','Craft improves through additional work and honest audience response.')],'X–XII')
].map((x,i)=>({...x,id:i,act:Math.floor(i/4)}));

export const glossary = [
['Action','Visible behavior or audible events described in a screenplay.'],['Beat','A small shift in action, intention, information, or power.'],['Climax','The decisive high point of the central conflict.'],['Conflict','Resistance between a pursuit and something that blocks or complicates it.'],['Dialogue','The words spoken by characters.'],['Dramatic irony','The audience knows something a character does not.'],['EXT.','Exterior: a scene outside.'],['INT.','Interior: a scene inside.'],['Inciting incident','The disruption that sets the central pressure in motion.'],['Logline','One or two sentences describing the central dramatic engine.'],['Need','An underlying change or recognition explored through the pursuit.'],['O.S.','Off screen: a speaker belongs to the scene but is not visible in the shot.'],['Payoff','The later use or transformation of an earlier planted detail.'],['Plant','A detail introduced earlier so a later event is prepared.'],['Protagonist','The central person whose pursuit or experience organizes the story.'],['Scene heading','A line identifying inside/outside, location, and time.'],['Stakes','What can be lost or gained because of the outcome.'],['Subtext','Intention or meaning beneath the literal words.'],['Suspense','Anticipation shaped by hope and fear about an outcome.'],['Tactic','A method a character uses to pursue a goal.'],['Theme','A question or idea explored through the events.'],['Treatment','A prose account of the film’s essential events, including the ending.'],['Turn','A meaningful change within a scene.'],['V.O.','Voice over: narration or speech not presented as ordinary dialogue from the visible scene.'],['Want','The goal the character actively pursues.']
];
export const drills=[
 {name:'Steal the spine',minutes:30,prompt:'Choose a short you can legally watch. Record title and creator. Identify before, disruption, attempts, decisive move, final image, want, and inner tension. Invent a different premise using only its pressure pattern.',checks:['I named specific moments from the film.','My new premise changes the people and situation.']},
 {name:'The closed loop',minutes:20,prompt:'Write almost the same opening and closing image with different meanings. Add three causal beats that make the meaning change.',checks:['The changed meaning is visible.','The three beats earn the change.']},
 {name:'Want in the room',minutes:15,prompt:'Two people, one room, incompatible wants. Write a short confrontation with at least two tactics and a turn. Cut redundant lines while preserving clarity.',checks:['Both people pursue something.','A changed tactic causes a turn.']},
 {name:'The silent page',minutes:20,prompt:'Write a complete scene with no dialogue. A task meets resistance. A choice changes its meaning. Use behavior, space, objects, and sound.',checks:['The action is filmable.','Something meaningful changes.']},
 {name:'Kill the explanation',minutes:15,prompt:'Paste a passage you wrote. Identify explanatory lines. Rewrite it using selected behavior or sound. Keep any spoken information the audience genuinely needs.',checks:['I preserved necessary orientation.','The rewrite gives actors actions to play.']}
];
export const sequences=[
['The spare key',['Mara needs to leave, but her key is missing.','She asks Eli; he insists he has not seen it.','She hears the key rattle in his pocket.','Confronted with the lie, Eli admits he fears being left.','Mara takes her key and gives him a time she will return.']],
['The last cake',['The baker has one cake for her daughter’s birthday.','A customer offers enough money to cover the overdue rent.','She agrees, but her daughter arrives early and sees the box.','The baker admits why she sold it instead of inventing an excuse.','They light a candle on the leftover slice together.']],
['The letter',['A son arrives to apologize before his mother’s train leaves.','He cannot say it, so he slips a letter into her bag.','She gives him the bag to hold while she boards.','He realizes silence will send the letter home with him.','He calls out the apology as the doors begin to close.']],
['The radio',['Nora wants to sell her father’s radio by noon.','The buyer asks to hear it work.','Nora repairs a wire and hears a familiar station.','She starts to withdraw the sale, but sees the empty shelf she has prepared.','She turns down the volume and hands the radio over.']]
];
export const reviewItems=[
['goal','A clear pursuit','Cite a scene where we can tell what the protagonist is trying to do.'],
['pressure','Resistance with consequences','Cite the obstacle, urgency, and personal cost.'],
['cause','A connected progression','Explain how one choice changes the next available action.'],
['change','An earned ending','Compare the first and last moments; name the difference and what earned it.'],
['filmable','Visible and audible storytelling','Cite behavior or sound carrying meaning that prose explanation used to carry.'],
['voices','Purposeful dialogue or silence','Cite a line’s tactic, or explain how a silent exchange works.'],
['reader','A tested draft','Record what a reader or rehearsal revealed, not just that it happened.'],
['rewrite','A meaningful revision','Explain one substantial before/after change and its intended effect.'],
['practical','A manageable film','List essential cast, accessible places, props, sound, and any unresolved production challenge.'],
['time','Runtime checked','Record approximate read/staging duration, including pauses and action.']
];

reviewItems.push(['coverage','Clear visual coverage','Cite how your frames establish geography and connect a cause to its reaction. If you deliberately withhold a view, explain why.'],['dialogueTactic','Dialogue pursues a want','Cite a tagged dialogue beat: what the character wants, the tactic used, and the resulting action. A purposeful silent beat counts.']);
