import {assets} from './assets.js?v=20260926-studio2';
import {cameraLessons,dialogueQuestions} from './camera.js?v=20260926-studio2';
import {coachPacks} from './coaches.js?v=20260926-studio2';
import {newId,migrateProject,frame,seedFrames,sizes,angles,perspectives,moves,tactics,collectNotes,clipNote,appendDraft,useInScene,shotList,promptSheet} from './studio-model.js?v=20260926-studio2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,id='',extra='')=>`<button class="btn small" data-studio-action="${action}" data-id="${esc(id)}" ${extra}>${text}</button>`;
const field=(label,value,attrs,area=false)=>`<label class="studio-field"><span>${label}</span>${area?`<textarea ${attrs}>${esc(value)}</textarea>`:`<input ${attrs} value="${esc(value)}">`}</label>`;
const select=(label,value,values,attrs)=>`<label class="studio-field"><span>${label}</span><select ${attrs}>${values.map(v=>{const [key,text]=Array.isArray(v)?v:[v,v];return `<option value="${esc(key)}" ${value===key?'selected':''}>${esc(text)}</option>`;}).join('')}</select></label>`;
let api,selectedScene='',coachAct=0,coachNode='',cameraIndex=0,cameraFeedback={},practice=null;
const p=()=>migrateProject(api.project());
const scene=()=>p().scenes.find(s=>s.id===selectedScene)||p().scenes[0];
const sceneOptions=()=>p().scenes.map((s,i)=>[s.id,`${i+1}. ${s.heading||'Untitled scene'}`]);
const rosterOptions=()=>[['','No character selected'],...p().characters.map(c=>[c.id,c.name||'Unnamed character'])];
const changed=(redraw=false)=>{p().updated=Date.now();p().reviewedAt=null;const ok=api.save();const status=document.querySelector('#save-status');if(status)status.textContent=ok?'Saved on this browser':'Not saved — export a backup';if(redraw)api.render();return ok;};
export function setupStudio(callbacks){api=callbacks;document.addEventListener('click',onClick);document.addEventListener('input',onInput);document.addEventListener('change',onChange);}
export function studioView(tab){p();return tab==='story'?storyView():tab==='storyboard'?boardView():tab==='dialogue'?dialogueView():tab==='coach'?coachView():tab==='camera'?cameraView():'';}
export const studioTabs=[['story','Notes → Story'],['storyboard','Storyboard'],['dialogue','Dialogue & cast'],['coach','Ask me'],['camera','Camera lessons']];
export function sceneTools(s){return `<div class="row spacer">${button('Board this scene','board-scene',s.id)}${button('Craft the dialogue','dialogue-scene',s.id)}${button('Ask me','coach-scene',s.id)}</div>${s.sourceNotes?.length?`<details class="spacer"><summary>Source notes (${s.sourceNotes.length})</summary>${s.sourceNotes.map(n=>`<p class="fine">${esc(n.source)}</p><p class="preserve">${esc(n.text)}</p>`).join('')}</details>`:''}`;}
export function entryTools(){return `<div class="notice studio-entry"><b>Your mission writing can become your story.</b><p>Collect your notes, arrange them, then shape a draft. Your original mission answers stay available.</p><div class="row">${button('Build from my notes','go','story')}${button('Ask me questions','go','coach')}${button('Learn camera choices','go','camera')}</div></div>`;}
function notes(){return collectNotes(p(),api.lessons,api.profile().drills,api.drills);}
function storyView(){const n=notes();return `<section class="card"><h2>From your notes to your story</h2><p>Choose ideas worth keeping. Arrange excerpts below, then add them to your editable story draft. This collects your own words; you decide how they connect.</p><p class="fine">Mission and coach notes belong to this film. Practice pages belong to your writer profile, so you may reuse them in any film.</p><details class="spacer" open><summary>Choose source notes (${n.length})</summary><div class="note-library">${n.length?n.map((x,i)=>`<article class="note-source"><h3>${esc(x.label)}</h3><p class="preserve">${esc(x.text)}</p>${button('Collect this note','clip',i)}</article>`).join(''):'<p>Write in a mission’s “Your film” step, or answer an Ask-me question. Your writing will appear here automatically.</p>'}</div></details></section><section class="card spacer"><h2>My selected notes</h2><p class="fine">These are editable copies. Revising a source later will not replace a collected excerpt.</p>${p().noteClips.map((c,i)=>`<article class="note-source"><div class="row spread"><b>${esc(c.label)}</b><div class="row">${button('↑','clip-up',c.id,`aria-label="Move note ${i+1} up" ${i===0?'disabled':''}`)}${button('↓','clip-down',c.id,`aria-label="Move note ${i+1} down" ${i===p().noteClips.length-1?'disabled':''}`)}${button('Remove copy','clip-remove',c.id)}</div></div>${field('Excerpt',c.text,`data-clip="${c.id}"`,true)}${button('Add excerpt to story draft','clip-draft',c.id)} ${button('Use excerpt in a scene','clip-scene',c.id)}</article>`).join('')||'<p>No notes collected yet.</p>'}${button('Append arranged notes to draft','assemble','',p().noteClips.length?'':'disabled')}</section><section class="card spacer"><h2>My story draft</h2><p>Shape the selected ideas into a beginning, attempts, a decisive choice, and an ending. You can write a prose story here before building screenplay scenes.</p>${field('Story draft',p().storyDraft,'data-story-draft class="story-editor"',true)}<div class="row">${button('Save story version','story-version')}${button('Download story (.txt)','story-export')}${button('Use a draft passage in a scene','draft-scene')}</div><details class="spacer"><summary>Saved story versions (${p().storyVersions.length})</summary>${p().storyVersions.map((v,i)=>`<article class="note-source"><b>${esc(new Date(v.date).toLocaleString())}</b><p class="preserve">${esc(v.text)||'(Empty draft)'}</p>${button('Restore this version','story-restore',i)}</article>`).join('')}</details></section>`;}
function transferModal(text,source){api.modal(`<h2>Use your writing in a scene</h2><p>Edit this copy first. Your original writing stays intact.</p>${field('Passage',text,'id="transfer-text"',true)}${select('Destination scene','new',[['new','Create a new scene'],...sceneOptions()],'id="transfer-scene"')}${select('Use as','notes',[['notes','Private planning note'],['action','Visible or audible action']],'id="transfer-target"')}<p class="fine">Choose action only for things the audience can see or hear. Planning notes stay out of screenplay exports.</p><input type="hidden" id="transfer-source" value="${esc(source)}">${button('Add to scene','transfer')}`);}
function boardView(){const s=scene();return `<section class="card"><div class="row spread"><div><h2>Storyboard Studio</h2><p>Each frame belongs to a screenplay scene. Images are optional; captions carry the story.</p></div>${button('Camera lessons','go','camera')}</div>${select('Scene',s.id,sceneOptions(),'data-studio-select="scene"')}<p class="preserve">${esc(s.action)||'Draft the scene in Screenplay, then plan what the audience sees.'}</p><div class="row">${button('Seed wide / medium / close','seed',s.id,s.frames.length?'disabled':'')}${button('+ Blank frame','add-frame',s.id)}${button('Ask me','go','coach')}${button('Shot list (.md)','shot-list')}${button('Board preview / PDF','board-print')}${button('Image prompts (.md)','prompts')}</div><p class="fine spacer">Starter artwork is included free. Uploads stay on this browser. Download a full backup to preserve pictures when moving devices.</p></section>${s.frames.length&&!s.frames.some(f=>f.shotSize==='WS')?'<p class="notice">There is no wide view in this scene. Is the geography already clear? A close opening can work if withholding the room is intentional.</p>':''}<div class="board-grid spacer">${s.frames.map((f,i)=>frameCard(s,f,i)).join('')||'<div class="card empty"><h3>Give this scene its first views.</h3><p>Seed three editable frames, or add a blank frame and choose what matters.</p></div>'}</div>`;}
function frameCard(s,f,i){const a=`data-frame="${f.id}"`;return `<article class="card frame-card"><div class="row spread"><h3>Frame ${i+1}</h3><div class="row">${button('↑','frame-up',f.id,`${i===0?'disabled':''} aria-label="Move frame ${i+1} up"`)}${button('↓','frame-down',f.id,`${i===s.frames.length-1?'disabled':''} aria-label="Move frame ${i+1} down"`)}${button('Remove','frame-remove',f.id)}</div></div><div class="frame-image">${f.imageRef?`<img src="${esc(f.imageRef)}" alt="${esc(f.caption||'Storyboard planning image')}">`:'<span>Blank frame · describe the action below</span>'}</div><div class="row">${button('Starter images','pick-image',f.id)}<label class="btn small">Upload image<input type="file" accept="image/png,image/jpeg,image/webp" data-frame-upload="${f.id}" class="upload-input"></label>${button('Clear image','clear-image',f.id)}</div><div class="mini-grid">${select('Shot size',f.shotSize,sizes,`${a} data-prop="shotSize"`)}${select('Angle',f.angle,angles,`${a} data-prop="angle"`)}${select('Perspective',f.perspective,perspectives,`${a} data-prop="perspective"`)}${select('Movement',f.move,moves,`${a} data-prop="move"`)}${field('Seconds',f.duration,`${a} data-prop="duration" type="number" min="1" max="120"`)}${select('Transition',f.transition,['Cut','Dissolve','Fade'],`${a} data-prop="transition"`)}</div>${field('What we see / hear',f.caption,`${a} data-prop="caption"`,true)}${select('Character',f.characterId,rosterOptions(),`${a} data-prop="characterId"`)}${field('Dialogue or silent beat',f.dialogueBeat,`${a} data-prop="dialogueBeat"`,true)}<details><summary>Optional image-generator prompt</summary>${field('Prompt',f.aiPrompt,`${a} data-prop="aiPrompt"`,true)}${button('Fill from frame choices','fill-prompt',f.id)}<p class="fine">Export and paste into a generator you choose. No generation service is called by StoryForge.</p></details></article>`;}
function imagePicker(id){api.modal(`<h2>Free starter images</h2><p>Planning symbols, not finished film stills. Select one image for the frame.</p>${['Poses','Places','Emotions','Objects'].map(cat=>`<h3 class="spacer">${cat}</h3><div class="asset-grid">${assets.filter(a=>a.category===cat).map(a=>`<button class="asset-choice" data-studio-action="set-image" data-id="${id}" data-ref="${a.ref}"><img src="${a.ref}" alt=""><span>${a.name}</span></button>`).join('')}</div>`).join('')}`);}
function dialogueView(){const s=scene();return `<section class="card"><h2>Dialogue is an action</h2><p><b>Want:</b> what the speaker tries to get right now. <b>Tactic:</b> how they pursue it. <b>Subtext:</b> what they mean but cannot say directly. A <b>beat</b> is a small unit of intention or change. A look or silence can do the work of a line.</p><p class="fine">Write an original line, then try a rewrite. Read both aloud and choose. Nothing is inserted into your screenplay until you ask.</p>${select('Scene',s.id,sceneOptions(),'data-studio-select="scene"')}<details><summary>Current scene dialogue</summary><p class="preserve">${esc(s.dialogue)||'No dialogue yet.'}</p></details>${button('+ Add dialogue beat','add-beat')}</section>${s.beats.map(b=>`<section class="card spacer"><div class="row spread"><h3>Line workshop</h3>${button('Remove beat','remove-beat',b.id)}</div>${select('Speaker',b.characterId,rosterOptions(),`data-beat="${b.id}" data-prop="characterId"`)}${field('What do they want in this beat?',b.want,`data-beat="${b.id}" data-prop="want"`)}${select('Tactic',b.tactic,tactics,`data-beat="${b.id}" data-prop="tactic"`)}${field('What cannot they say directly?',b.subtext,`data-beat="${b.id}" data-prop="subtext"`,true)}<div class="mini-grid">${field('Original line',b.original,`data-beat="${b.id}" data-prop="original"`,true)}${field('Rewritten line',b.rewrite,`data-beat="${b.id}" data-prop="rewrite"`,true)}</div>${field('Silent alternative: visible behavior',b.silentAction,`data-beat="${b.id}" data-prop="silentAction"`,true)}<div class="row">${button('Append original to scene','beat-original',b.id)}${button('Append rewrite to scene','beat-rewrite',b.id)}${button('Use silent action instead','beat-silence',b.id)}</div></section>`).join('')}<section class="card spacer"><h2>Character voice sheets</h2><p>Lexicon means the words a person tends to choose. Rhythm means the pace and shape of speech. A taboo is something they avoid saying.</p>${button('+ Add character','add-character')}${p().characters.map(c=>`<article class="note-source">${['name','want','lexicon','rhythm','taboo'].map(k=>field(k[0].toUpperCase()+k.slice(1),c[k],`data-character="${c.id}" data-prop="${k}"`)).join('')}${select('Reference pose',c.silhouette,[['','None'],...assets.filter(a=>a.category==='Poses').map(a=>[a.ref,a.name])],`data-character="${c.id}" data-prop="silhouette"`)}</article>`).join('')}</section>`;}
function coachView(){const pack=coachPacks[coachAct],node=pack.nodes.find(n=>n.id===coachNode);return `<section class="card"><h2>Ask me: find your next choice</h2><p>These questions help you discover your story. Answers become project notes that you can collect in Notes → Story.</p>${select('Coach act',String(coachAct),api.acts.map((a,i)=>[String(i),`Act ${i+1}: ${a.name}`]),'data-studio-select="coach-act"')}<div class="coach-choices">${pack.nodes.filter(n=>n.next.length===2).map(n=>button(esc(n.question),'coach-node',n.id)).join('')}</div></section>${node?`<section class="card spacer"><h2>${esc(node.question)}</h2>${field('Your answer',p().coachNotes[node.id]||'',`data-coach="${node.id}"`,true)}<h3>Explore a follow-up</h3><div class="row">${node.next.map(id=>button(esc(pack.nodes.find(n=>n.id===id).question),'coach-node',id)).join('')||'<p>Return to a starting question, or collect this answer into your story.</p>'}${button('Collect answer into my notes','coach-clip',node.id)}</div></section>`:'<p class="notice spacer">Choose the question closest to where you are stuck. Try an answer in ordinary language.</p>'}<section class="card spacer"><h3>Boarding a scene?</h3><p>Do we need geography before this close view? Whose eyes should we be in? What changes between this frame and the next?</p>${button('Open storyboard','go','storyboard')}</section>`;}
function shotDiagram(choice){const human='<circle cx="160" cy="67" r="23"/><path d="M136 96Q160 86 184 96L196 160H124Z"/>';let drawing='';
if(choice==='POV')drawing='<path d="M45 115H290L265 165H20Z" fill="#b9c8b0"/><circle cx="165" cy="124" r="12" fill="none" stroke="#355849" stroke-width="5"/><path d="M177 124H215V135M201 124V134" stroke="#355849" stroke-width="5"/><path d="M0 175 90 145 115 153 82 180" fill="#355849"/>';
else if(choice==='Low')drawing='<path d="M30 180 115 0M290 180 205 0" stroke="#9aaf9d" stroke-width="4"/><g fill="#355849"><circle cx="160" cy="56" r="18"/><path d="M144 78H176L223 180H97Z"/></g><path d="M20 130V80m-7 12 7-12 7 12" stroke="#355849" fill="none" stroke-width="4"/>';
else {const size=choice==='CU'?2.6:choice==='MS'?1.4:1;drawing='<path d="M20 160V15H85V160M0 160H320" fill="none" stroke="#9aaf9d" stroke-width="4"/>'+`<g transform="translate(${160-160*size} ${choice==='CU'?-110:180-180*size}) scale(${size})" fill="#365849">${human}</g>`;if(choice==='OTS')drawing+='<path d="M0 180V110Q50 40 92 180" fill="#182e26"/>';}
return `<svg viewBox="0 0 320 180" role="img" aria-label="${esc(choice)} framing example"><rect width="320" height="180" fill="#e5e9db"/>${drawing}<rect x="8" y="5" width="90" height="30" rx="5" fill="#edf0df"/><text x="14" y="27" font-size="19" fill="#182e26">${choice}</text></svg>`;}

function cameraView(){const l=cameraLessons[cameraIndex];return `<section class="card"><h2>Camera choices: a parallel mini-track</h2><p>Use these lessons alongside your writing quest. Complete both checks and apply each idea to your own frames.</p><div class="row">${cameraLessons.map((l,i)=>button(`${p().cameraProgress[l.id]?'✓ ':''}${l.title}`,'camera-lesson',i)).join('')}</div></section><section class="card spacer"><h2>${l.title}</h2><p>${l.text}</p><div class="mini-grid camera-pair">${l.pair.map((choice,i)=>`<figure>${shotDiagram(choice)}<figcaption>${i?l.after:l.before}</figcaption></figure>`).join('')}</div>${l.questions.map((q,i)=>`<fieldset class="camera-question"><legend>${q[0]}</legend>${q[1].map((text,j)=>button(esc(text),'camera-answer',`${i}:${j}`)).join('')}${cameraFeedback[l.id+':'+i]!==undefined?`<p role="status" class="notice">${cameraFeedback[l.id+':'+i]?'Correct.':'Try again.'} ${q[3]}</p>`:''}</fieldset>`).join('')}<h3 class="spacer">Apply it to your film</h3><p>${l.task}</p>${field('What did you choose and why?',p().coachNotes['camera-'+l.id]||'',`data-coach="camera-${l.id}"`,true)}${button('Record camera lesson','camera-complete')}${button('Open storyboard','go','storyboard')}</section>`;}
export function arcadeEntries(){return `<section class="card spacer"><h2>Camera & dialogue practice</h2><p>Choose a shot for meaning, or identify what a line is doing.</p><div class="row">${button('Play Shot Choice','practice-start','shots')}${button('Play Dialogue Tactics','practice-start','dialogue')}</div></section>`;}
function practiceModal(){const q=practice.questions[practice.index];api.closeModal();api.modal(`<h2>${practice.mode==='shots'?'Shot Choice':'Dialogue Tactics'} · ${practice.index+1}/${practice.questions.length}</h2><p>${q[0]}</p>${q[1].map((t,i)=>button(esc(t),'practice-answer',i,practice.answered?'disabled':'')).join('')}${practice.answered?`<div class="notice spacer">${practice.correct?'Correct.':'Try this reasoning:'} ${q[3]}</div>${button('Review the lesson','practice-lesson',practice.lessonIndex??0)}${button(practice.index+1===practice.questions.length?'Finish round':'Next question','practice-next')}`:''}`);}
export function boardHTML(project){return `<h1>${esc(project.title)} — Storyboard</h1><p>Frames are planning references. Estimated duration: ${project.scenes.flatMap(s=>s.frames).reduce((a,f)=>a+f.duration,0)} seconds.</p>${project.scenes.map((s,i)=>`<h2>Scene ${i+1}: ${esc(s.heading)}</h2><div class="print-board-grid">${s.frames.map((f,j)=>`<figure class="print-frame">${f.imageRef?`<img src="${esc(f.imageRef)}" alt="${esc(f.caption)}">`:'<div class="blank-panel">Blank frame</div>'}<figcaption><b>${j+1}. ${f.shotSize} · ${f.angle} · ${f.perspective}</b><p>${esc(f.move)} · ${f.duration}s · ${esc(f.transition)}</p><p class="preserve">${esc(f.caption)}</p><p class="preserve">${esc(f.dialogueBeat)}</p></figcaption></figure>`).join('')||'<p>No frames yet.</p>'}</div>`).join('')}`;}
const findFrame=id=>p().scenes.flatMap(s=>s.frames).find(f=>f.id===id);
const move=(items,id,delta)=>{const i=items.findIndex(x=>x.id===id),j=i+delta;if(i>=0&&j>=0&&j<items.length)[items[i],items[j]]=[items[j],items[i]];};
async function onClick(e){const el=e.target.closest('[data-studio-action]');if(!el||el.disabled)return;const a=el.dataset.studioAction,id=el.dataset.id;let redraw=true;
 switch(a){
 case 'go':api.go(id);return;
 case 'clip':clipNote(p(),notes()[Number(id)]);api.toast('Note collected. The source is preserved.');break;
 case 'clip-up':case 'clip-down':move(p().noteClips,id,a==='clip-up'?-1:1);break;
 case 'clip-remove':p().noteClips=p().noteClips.filter(c=>c.id!==id);break;
 case 'clip-draft':appendDraft(p(),p().noteClips.find(c=>c.id===id).text);break;
 case 'assemble':appendDraft(p(),p().noteClips.map(c=>c.text).join('\n\n'));api.toast('Your notes were appended. Edit them into a connected story.');break;
 case 'clip-scene':{const c=p().noteClips.find(c=>c.id===id);transferModal(c.text,c.label);return;}
 case 'draft-scene':transferModal(p().storyDraft,'Story draft');return;
 case 'transfer':{const text=document.querySelector('#transfer-text').value.trim();if(!text){api.toast('Add a passage first.');return;}const dest=document.querySelector('#transfer-scene').value;const s=dest==='new'?api.blankScene():p().scenes.find(s=>s.id===dest);if(dest==='new'){migrateProject({scenes:[s]});p().scenes.push(s);}useInScene(s,text,document.querySelector('#transfer-source').value,document.querySelector('#transfer-target').value);api.closeModal();changed();api.go('screenplay');return;}
 case 'story-version':p().storyVersions.push({date:new Date().toISOString(),text:p().storyDraft});api.toast('Story version saved.');break;
 case 'story-restore':{const text=p().storyVersions[Number(id)].text;p().storyVersions.push({date:new Date().toISOString(),text:p().storyDraft});p().storyDraft=text;break;}
 case 'story-export':api.download(api.slug(p().title)+'_story.txt',p().storyDraft);return;
 case 'board-scene':selectedScene=id;seedFrames(scene());changed();api.go('storyboard');return;
 case 'dialogue-scene':selectedScene=id;api.go('dialogue');return;
 case 'coach-scene':selectedScene=id;coachAct=4;coachNode='act5-1';api.go('coach');return;
 case 'seed':seedFrames(scene());break;
 case 'add-frame':if(scene().frames.length>=100){api.toast('This scene has the maximum of 100 frames.');return;}scene().frames.push(frame(scene().id));break;
 case 'frame-up':case 'frame-down':move(scene().frames,id,a==='frame-up'?-1:1);break;
 case 'frame-remove':api.modal(`<h2>Remove this frame?</h2><p>The caption and image will be removed from this board. Export a backup first if you want to preserve it.</p>${button('Remove frame','frame-remove-confirm',id)}`);return;
 case 'frame-remove-confirm':scene().frames=scene().frames.filter(f=>f.id!==id);api.closeModal();break;
 case 'pick-image':imagePicker(id);return;
 case 'set-image':findFrame(id).imageRef=el.dataset.ref;api.closeModal();break;
 case 'clear-image':findFrame(id).imageRef='';break;
 case 'fill-prompt':{const f=findFrame(id);f.aiPrompt=`Storyboard reference, ${f.shotSize}, ${f.angle}, ${f.perspective}, ${f.move}. ${f.caption}`;break;}
 case 'shot-list':api.download(api.slug(p().title)+'_shot-list.md',shotList(p()),'text/markdown');return;
 case 'prompts':api.download(api.slug(p().title)+'_prompts.md',promptSheet(p()),'text/markdown');return;
 case 'board-print':api.modal(`<h2>Board preview</h2><p>Print this board or choose Save as PDF in your browser’s print dialog.</p>${button('Print / save board PDF','print-board')}<div class="board-preview">${boardHTML(p())}</div>`);return;
 case 'print-board':{document.querySelector('.print-only')?.remove();const section=document.createElement('section');section.className='print-only board-print';section.innerHTML=boardHTML(p());document.body.append(section);await Promise.all([...section.querySelectorAll('img')].map(img=>img.decode().catch(()=>{})));window.print();return;}
 case 'add-character':p().characters.push({id:newId(),name:'',want:'',lexicon:'',rhythm:'',taboo:'',silhouette:''});break;
 case 'add-beat':scene().beats.push({id:newId(),characterId:'',want:'',tactic:'Ask',subtext:'',original:'',rewrite:'',silentAction:''});break;
 case 'remove-beat':scene().beats=scene().beats.filter(b=>b.id!==id);break;
 case 'beat-original':case 'beat-rewrite':case 'beat-silence':{const b=scene().beats.find(b=>b.id===id),key=a==='beat-original'?'original':a==='beat-rewrite'?'rewrite':'silentAction';const text=b[key].trim();if(!text){api.toast('Write the selected version first.');return;}if(a==='beat-silence')scene().action=[scene().action,text].filter(Boolean).join('\n\n');else{const c=p().characters.find(c=>c.id===b.characterId);if(!c?.name.trim()){api.toast('Choose a named speaker from your voice sheets first.');return;}scene().dialogue=[scene().dialogue,`${c.name.toUpperCase()}\n${text}`].filter(Boolean).join('\n\n');}api.toast('Appended to your screenplay.');break;}
 case 'coach-node':coachNode=id;api.render();return;
 case 'coach-clip':{const text=p().coachNotes[id];if(!text?.trim()){api.toast('Write an answer first.');return;}const node=coachPacks[coachAct].nodes.find(n=>n.id===id);clipNote(p(),{source:'coach:'+id,label:node.question,text});api.toast('Answer collected in Notes → Story.');break;}
 case 'camera-lesson':cameraIndex=Number(id);api.render();return;
 case 'camera-answer':{const [i,j]=id.split(':').map(Number),l=cameraLessons[cameraIndex];cameraFeedback[l.id+':'+i]=l.questions[i][2]===j;api.render();return;}
 case 'camera-complete':{const l=cameraLessons[cameraIndex];if(!l.questions.every((_,i)=>cameraFeedback[l.id+':'+i])||(p().coachNotes['camera-'+l.id]||'').trim().split(/\s+/).length<8){api.toast('Answer both checks correctly and explain your choice in at least 8 words.');return;}p().cameraProgress[l.id]=true;api.toast('Camera lesson recorded.');break;}
 case 'practice-start':{const qs=id==='shots'?cameraLessons.flatMap((l,i)=>l.questions.map(q=>[...q,i])):dialogueQuestions.map(q=>[...q,4]);practice={mode:id,questions:api.shuffle(qs),index:0,score:0,answered:false};practiceModal();return;}
 case 'practice-answer':if(practice.answered)return;practice.correct=Number(id)===practice.questions[practice.index][2];practice.answered=true;practice.lessonIndex=practice.questions[practice.index][4];if(practice.correct)practice.score+=10;practiceModal();return;
 case 'practice-lesson':api.closeModal();if(practice.mode==='dialogue')api.go('dialogue');else{cameraIndex=Number(id);api.go('camera');}return;
 case 'practice-next':if(++practice.index>=practice.questions.length){api.profile().arcade.best[practice.mode]=Math.max(api.profile().arcade.best[practice.mode]||0,practice.score);api.save();api.closeModal();api.modal(`<h2>Round complete · ${practice.score} XP</h2><p>Review the explanations, then apply one choice to your film.</p>${button('Open camera lessons','go','camera')}${button('Open dialogue workshop','go','dialogue')}`);api.render();return;}practice.answered=false;practiceModal();return;
 default:return;
 }
 changed(redraw);
}
function onInput(e){const el=e.target;let dirty=true;
 if(el.hasAttribute('data-story-draft'))p().storyDraft=el.value;
 else if(el.dataset.clip)p().noteClips.find(c=>c.id===el.dataset.clip).text=el.value;
 else if(el.dataset.coach)p().coachNotes[el.dataset.coach]=el.value;
 else if(el.dataset.frame){const f=findFrame(el.dataset.frame);if(!f)return;f[el.dataset.prop]=el.dataset.prop==='duration'?Math.max(1,Math.min(120,Number(el.value)||1)):el.value;}
 else if(el.dataset.character)p().characters.find(c=>c.id===el.dataset.character)[el.dataset.prop]=el.value;
 else if(el.dataset.beat)scene().beats.find(b=>b.id===el.dataset.beat)[el.dataset.prop]=el.value;
 else dirty=false;
 if(dirty)changed();
}
async function onChange(e){const el=e.target;
 if(el.dataset.studioSelect==='scene'){selectedScene=el.value;api.render();}
 if(el.dataset.studioSelect==='coach-act'){coachAct=Number(el.value);coachNode='';api.render();}
 if(el.dataset.frameUpload&&el.files[0]){const file=el.files[0],f=findFrame(el.dataset.frameUpload);const targetProject=p();if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){api.toast('Choose a PNG, JPEG, or WebP image no larger than 2 MB.');el.value='';return;}
 const uploaded=targetProject.scenes.flatMap(s=>s.frames).filter(x=>x!==f&&x.imageRef.startsWith('data:'));if(uploaded.length>=12){api.toast('Use up to 12 uploaded images per film. Starter images are unlimited.');return;}
 try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas'),scale=Math.min(1,800/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/jpeg',0.75);if(uploaded.reduce((n,x)=>n+x.imageRef.length,0)+data.length>1600000)throw Error('This film has reached its local image budget. Remove an uploaded image or choose a simpler one.');const previous=f.imageRef;f.imageRef=data;if(!api.save()){f.imageRef=previous;api.toast('Image could not be saved. Export a backup or free browser storage.');}else api.toast('Image saved locally. Metadata was removed.');api.render();}catch(err){api.toast(err.message||'Could not open this image.');}el.value='';}
}
